<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_082297334277 - Farma  Reguler Member</name>
   <tag></tag>
   <elementGuidId>e2d6fa26-f8d6-4c50-92eb-75744256a8d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='Farma']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;Farma&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dd5432fe-67bf-45e2-8d5f-bc3f7125a807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id-customer</name>
      <type>Main</type>
      <value>557</value>
      <webElementGuid>72f2ea80-20e4-4c91-a0f7-e2e8b2586e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>username</name>
      <type>Main</type>
      <value>kukuhwicaksono105xb03Mg</value>
      <webElementGuid>9192c79c-2a89-42ad-bcc3-4d395b8cbc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>email</name>
      <type>Main</type>
      <value>kukuhwicaksono105xb@gmail.com</value>
      <webElementGuid>0e9496ee-4c31-4f7a-932c-5f04e7ae8869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Farma</value>
      <webElementGuid>ee6b3570-1bc1-47ea-b47e-45f4ac3236b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gender</name>
      <type>Main</type>
      <value>FEMALE</value>
      <webElementGuid>41a02938-a7db-4ab9-880f-cd0aa81de8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>phone</name>
      <type>Main</type>
      <value>+6282297334277</value>
      <webElementGuid>40f46c9b-8399-49a5-a82a-25f075822ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is_barcode</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>40e3d82f-6879-4b6c-aaca-47d884c3b813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cluster</name>
      <type>Main</type>
      <value>BASE</value>
      <webElementGuid>679bee42-0e41-40f2-bc52-582d53c9951e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>point</name>
      <type>Main</type>
      <value>7000</value>
      <webElementGuid>e0d0b530-1deb-4874-9ab4-279bfeec4440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>public_id</name>
      <type>Main</type>
      <value>C01ECG41Z47HU8</value>
      <webElementGuid>704cf66a-e008-45a5-9c28-3b3de3718264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>082297334277 - Farma  Reguler Member</value>
      <webElementGuid>3c1bd298-5bf0-4dc6-a95e-56864f6a4d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/div[@class=&quot;container-full&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col s6 payments&quot;]/div[@class=&quot;customer&quot;]/nav[@class=&quot;search col m12 z-depth-0&quot;]/div[@class=&quot;nav-wrapper&quot;]/form[1]/div[@class=&quot;input-field&quot;]/div[@class=&quot;search-results&quot;]/a[1]</value>
      <webElementGuid>624c3d97-68e6-4b89-9858-5c6ebb69c3ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='Farma']</value>
      <webElementGuid>0587ee06-60ad-40ea-bef6-38b82dee8352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home']/div/div/div[2]/div/nav/div/form/div/div[2]/a</value>
      <webElementGuid>07e39aac-9b02-4cbf-a3d3-fe9959ff03b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ON HOLD'])[1]/following::a[1]</value>
      <webElementGuid>a2310b37-5ea8-4d45-a984-685509ff6cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member'])[1]/following::a[2]</value>
      <webElementGuid>97204aa1-6547-4e76-8b4c-88d2636e9bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reguler Member'])[2]/preceding::a[1]</value>
      <webElementGuid>c286e5ab-c688-4dbe-ad87-30f0365c19de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='082297334277 - Farma']/parent::*</value>
      <webElementGuid>d50615ac-b81b-4298-82b8-2f9683352c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/a</value>
      <webElementGuid>dead2acf-5763-4fc2-a4b5-adb43860b715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'Farma' and (text() = '082297334277 - Farma  Reguler Member' or . = '082297334277 - Farma  Reguler Member')]</value>
      <webElementGuid>f81d8ca6-6ae7-4136-b583-15487d9448a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
