<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_082297334277 - Farma  Silver Member</name>
   <tag></tag>
   <elementGuidId>3af1cb36-d01b-4fb4-8032-d0efd8e34205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='Farma']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;Farma&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4c403110-5ea2-4ad1-8ebd-28e83cd9f4d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id-customer</name>
      <type>Main</type>
      <value>557</value>
      <webElementGuid>1909ff89-f657-4ea9-91b3-3e814901acae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>username</name>
      <type>Main</type>
      <value>kukuhwicaksono105xb03Mg</value>
      <webElementGuid>b101fb07-c8f0-4994-b185-ec70855af5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>email</name>
      <type>Main</type>
      <value>kukuhwicaksono105xb@gmail.com</value>
      <webElementGuid>2aea7568-ce08-40d6-9038-0d708df783e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Farma</value>
      <webElementGuid>723a897b-56f4-4a6d-9d46-3b0980873734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gender</name>
      <type>Main</type>
      <value>FEMALE</value>
      <webElementGuid>e5addbf9-e5e9-4b24-8ca3-4d67e772fdc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>phone</name>
      <type>Main</type>
      <value>+6282297334277</value>
      <webElementGuid>32c48572-9bea-43ef-9e03-4fd40881518f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is_barcode</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>886315a1-2f61-40a2-a1e4-d00a9d8a6413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cluster</name>
      <type>Main</type>
      <value>SILVER</value>
      <webElementGuid>d7577ec6-95d2-49ae-b2e4-f2ad9e9ef258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>point</name>
      <type>Main</type>
      <value>25000</value>
      <webElementGuid>2e144c9b-9250-4466-890f-66bc24afacbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>public_id</name>
      <type>Main</type>
      <value>C01ECG41Z47HU8</value>
      <webElementGuid>bca5968a-9da4-4206-9ca5-27f104796a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>082297334277 - Farma  Silver Member</value>
      <webElementGuid>3046fa7d-9c8c-443f-b42f-9871ab90eb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/div[@class=&quot;container-full&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col s6 payments&quot;]/div[@class=&quot;customer&quot;]/nav[@class=&quot;search col m12 z-depth-0&quot;]/div[@class=&quot;nav-wrapper&quot;]/form[1]/div[@class=&quot;input-field&quot;]/div[@class=&quot;search-results&quot;]/a[1]</value>
      <webElementGuid>e7fae98c-dcf2-4693-8910-e2d392a5a72c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='Farma']</value>
      <webElementGuid>74b83d9e-3945-4218-a1da-92f6285bd57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home']/div/div/div[2]/div/nav/div/form/div/div[2]/a</value>
      <webElementGuid>615ee19c-9dd7-4fb2-9ab2-faa3345c16c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ON HOLD'])[1]/following::a[1]</value>
      <webElementGuid>369fa0e9-d0bd-4001-8086-aae889bdb06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member'])[1]/following::a[2]</value>
      <webElementGuid>fcd623ec-ca72-49ca-ab72-9af0e0f0e931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reguler Member'])[1]/preceding::a[1]</value>
      <webElementGuid>b89572c1-0775-4468-9fb7-2932a318795e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='082297334277 - Farma']/parent::*</value>
      <webElementGuid>376eaef8-0d9e-4bf3-b421-58a216dbb56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/a</value>
      <webElementGuid>b738e7b1-6683-409e-a825-8af2ab83a2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'Farma' and (text() = '082297334277 - Farma  Silver Member' or . = '082297334277 - Farma  Silver Member')]</value>
      <webElementGuid>86653e16-056d-4610-930a-482b44d1ce88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
