<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_082297334277 - Farma  Silver Member</name>
   <tag></tag>
   <elementGuidId>3af1cb36-d01b-4fb4-8032-d0efd8e34205</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@name='Farma']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[name=&quot;Farma&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>720f9e29-fc06-485d-8377-643d72600e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id-customer</name>
      <type>Main</type>
      <value>557</value>
      <webElementGuid>3e2877ba-c6ea-4a42-8026-eeeedcbe90e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>username</name>
      <type>Main</type>
      <value>kukuhwicaksono105xb03Mg</value>
      <webElementGuid>b0735710-dc92-418d-ade5-c9eb98030bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>email</name>
      <type>Main</type>
      <value>kukuhwicaksono105xb@gmail.com</value>
      <webElementGuid>5fb1addd-a435-40cb-9d85-b8200dd13f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Farma</value>
      <webElementGuid>1da60cd9-c26b-4cdc-9d3c-fe21ef3faeef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gender</name>
      <type>Main</type>
      <value>FEMALE</value>
      <webElementGuid>afba380a-b6d0-41f1-854d-efbfe63148eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>phone</name>
      <type>Main</type>
      <value>+6282297334277</value>
      <webElementGuid>312818b0-8068-4a95-94c6-43a531f6fdf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>is_barcode</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>58820812-3677-4209-ae22-dddd740ae686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cluster</name>
      <type>Main</type>
      <value>SILVER</value>
      <webElementGuid>f29dcb60-fe44-45e1-8ccb-d4340f70ef9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>point</name>
      <type>Main</type>
      <value>34000</value>
      <webElementGuid>a2b2f7ae-69f0-4dbe-a159-feb4a0e54330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>public_id</name>
      <type>Main</type>
      <value>C01ECG41Z47HU8</value>
      <webElementGuid>badb246d-eb7c-4339-ab97-b9334110cf72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>082297334277 - Farma  Silver Member</value>
      <webElementGuid>21c04dec-270d-4ee1-9ad2-a933401a2b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/div[@class=&quot;container-full&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col s6 payments&quot;]/div[@class=&quot;customer&quot;]/nav[@class=&quot;search col m12 z-depth-0&quot;]/div[@class=&quot;nav-wrapper&quot;]/form[1]/div[@class=&quot;input-field&quot;]/div[@class=&quot;search-results&quot;]/a[1]</value>
      <webElementGuid>54bc0e52-8f30-408a-86f6-275cb8e6d603</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@name='Farma']</value>
      <webElementGuid>fc664ad0-1efc-4aed-be39-2d7f6b887750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home']/div/div/div[2]/div/nav/div/form/div/div[2]/a</value>
      <webElementGuid>330e3169-70dd-4eb9-b416-6e22afd110a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ON HOLD'])[1]/following::a[1]</value>
      <webElementGuid>0ce4d709-56a0-44ae-8cc1-95a3bfeabad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member'])[1]/following::a[2]</value>
      <webElementGuid>0954e669-e3b1-4038-8a15-51b316eaa204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reguler Member'])[1]/preceding::a[1]</value>
      <webElementGuid>6fb910c6-a527-430a-bda5-4b214fbf52ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='082297334277 - Farma']/parent::*</value>
      <webElementGuid>82ac3fca-e93c-456c-861a-49174604b057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/a</value>
      <webElementGuid>24812cc7-ed3e-4e6e-a40b-cab1737bda4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'Farma' and (text() = '082297334277 - Farma  Silver Member' or . = '082297334277 - Farma  Silver Member')]</value>
      <webElementGuid>8b64d4ca-3e51-49b7-9356-b6cc7af0a6f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
