<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Akhiri Sesi</name>
   <tag></tag>
   <elementGuidId>3fdc43fe-1164-4640-8ab3-79a4f0a69422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn-close-session']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-close-session</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a9f1520b-52de-4b55-9894-15c5ff5dcd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-close-session</value>
      <webElementGuid>e160565c-143f-4e8a-a1a3-d6445f90e7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-close-session</name>
      <type>Main</type>
      <value>data-close-session</value>
      <webElementGuid>b98fb80e-132f-4f7b-b0f5-f50c2f50a78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>waves-effect waves-light btn</value>
      <webElementGuid>b9d18b06-c165-417e-a85e-28b7a0bc390c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/session_manager/end_session_confirm</value>
      <webElementGuid>97dddbc3-66dc-46dc-af65-f69c855b12e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akhiri Sesi</value>
      <webElementGuid>49989302-3e67-4375-9e49-3b50a5811792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-close-session&quot;)</value>
      <webElementGuid>3b3f9c96-06e9-4b4f-a592-18613c4114f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn-close-session']</value>
      <webElementGuid>7439f7c7-77a7-4edf-81f8-885e8c58501d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='account']/div/div[3]/div[2]/a</value>
      <webElementGuid>0cd77ddb-f7f9-4b53-9e5b-9f695b237348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Akhiri Sesi')]</value>
      <webElementGuid>7c5fc1e5-4ca6-4f4d-a87c-2072c5b68b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ganti Kata Sandi'])[1]/following::a[1]</value>
      <webElementGuid>20c4c448-b40e-43c5-bc4d-cc52b093bce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manager'])[1]/following::a[2]</value>
      <webElementGuid>e36cccb1-a746-4646-b361-fe1b31faccd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::a[1]</value>
      <webElementGuid>624c4400-15e7-4fbf-bf04-8d3b334b611f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valid'])[1]/preceding::a[2]</value>
      <webElementGuid>57ded99c-94ba-41b6-8be0-d6f117330be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Akhiri Sesi']/parent::*</value>
      <webElementGuid>eed322e2-6c82-4c5c-8392-2a0a91330e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/session_manager/end_session_confirm')]</value>
      <webElementGuid>722054b8-dda6-4b18-a9da-75c2b9755ca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>5ffb3381-37f2-49e3-9248-47af0dd7868e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn-close-session' and @href = '/session_manager/end_session_confirm' and (text() = 'Akhiri Sesi' or . = 'Akhiri Sesi')]</value>
      <webElementGuid>b7178b71-447a-481c-9749-40434cf19a73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
