<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Akhiri Sesi</name>
   <tag></tag>
   <elementGuidId>3fdc43fe-1164-4640-8ab3-79a4f0a69422</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn-close-session']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-close-session</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>72d18caa-3704-43b5-932a-9b23e535241a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-close-session</value>
      <webElementGuid>c79c7e7a-5c6d-49e9-95f4-78919edc95fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-close-session</name>
      <type>Main</type>
      <value>data-close-session</value>
      <webElementGuid>0132d5f8-b9bd-4c71-a148-e58a9a52506c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>waves-effect waves-light btn</value>
      <webElementGuid>6be6cec8-8eba-445c-b7e2-9c6e55b63a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/session_manager/end_session_confirm</value>
      <webElementGuid>f2a8f2db-cf15-4a1b-8171-5e8d50f47689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Akhiri Sesi</value>
      <webElementGuid>43a49703-fb35-4586-975e-96454d9c4c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-close-session&quot;)</value>
      <webElementGuid>100384c6-bab7-44d8-9fc8-153af2b65648</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn-close-session']</value>
      <webElementGuid>83c6b56f-06c1-413b-bd60-91e05645b7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='account']/div/div[3]/div[2]/a</value>
      <webElementGuid>57bef5b2-3b23-49b5-a081-7ce3125b1a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Akhiri Sesi')]</value>
      <webElementGuid>f64fb5ec-edd3-4efa-8c95-132698c81122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ganti Kata Sandi'])[1]/following::a[1]</value>
      <webElementGuid>c61ecc81-924c-496f-a222-3edfff736ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manager'])[1]/following::a[2]</value>
      <webElementGuid>e22d9edf-eed9-47ac-809c-401536ad7a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::a[1]</value>
      <webElementGuid>2e50f121-4e23-4362-8519-994cd2416d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Valid'])[1]/preceding::a[2]</value>
      <webElementGuid>9fdc880e-4b49-412a-bd6a-bf3f0026a481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Akhiri Sesi']/parent::*</value>
      <webElementGuid>75692a40-3a6b-4951-81f8-451f1dc17c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/session_manager/end_session_confirm')]</value>
      <webElementGuid>0259879c-49b2-4863-a3c9-d80b05490ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>f2a5c2bf-f429-4058-abd9-897897cc1998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn-close-session' and @href = '/session_manager/end_session_confirm' and (text() = 'Akhiri Sesi' or . = 'Akhiri Sesi')]</value>
      <webElementGuid>48f57961-ad68-4ed2-b6b1-e3d920d41002</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
