<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CASH</name>
   <tag></tag>
   <elementGuidId>cbea8dc7-a6aa-4b41-9eb0-6d791e05b861</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment-method-container']/div/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>89d285e4-8210-496a-af1d-98f944f626ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#payment-cash-method</value>
      <webElementGuid>e1e6fe71-c015-4cb5-b6f3-655a59c95530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-payment-form</name>
      <type>Main</type>
      <value>payment-cash-method</value>
      <webElementGuid>6ccc035f-3a84-4356-8d98-f88873b6834c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>method-expres center-align </value>
      <webElementGuid>e6de5f5d-3bca-40e4-993e-aae80f0ac394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            
            CASH
        </value>
      <webElementGuid>3b151c64-c42a-46cc-91c5-74362982dc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-method-container&quot;)/div[@class=&quot;payment-methods center-align&quot;]/a[@class=&quot;method-expres center-align&quot;]</value>
      <webElementGuid>e8831d08-b80a-463a-a557-e3f4bc0e0432</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-method-container']/div/a[3]</value>
      <webElementGuid>15747218-5915-41e2-89f3-b1fe08cd321a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bayar Dengan Point'])[1]/preceding::a[2]</value>
      <webElementGuid>51b48fb9-7c99-465d-81f8-5f91487b791b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CASH']/parent::*</value>
      <webElementGuid>7385af7b-3fe4-4162-abc1-872aa0a04f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#payment-cash-method')]</value>
      <webElementGuid>56a86caa-1ed5-49b9-bad0-d006c7d63bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/div/div/a[3]</value>
      <webElementGuid>d66ef4be-1652-4384-a700-6c189e8109ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#payment-cash-method' and (text() = '
            
            CASH
        ' or . = '
            
            CASH
        ')]</value>
      <webElementGuid>1efbd7a4-e57b-4592-99a2-236f2b16f813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>f33bdce4-355c-40cd-a526-06e2c9f73db4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
