<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_FLUIMUCIL 200MG SACH30 (Stok 92, stock lock 0)</name>
   <tag></tag>
   <elementGuidId>1222d803-6f29-4f6a-9c61-f280aad646c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home']/div/div/div/div/nav/div/form/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.search-results-item > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5794361a-5e2a-4cef-8bbf-5646545c5d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-id-search</name>
      <type>Main</type>
      <value>140403217</value>
      <webElementGuid>93bc0cbe-9876-4a15-98b2-ff6e29f67172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FLUIMUCIL 200MG SACH@30 (Stok: 92, stock lock: 0)</value>
      <webElementGuid>9346f2a5-9f62-4c23-b10c-4fdd80512e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/div[@class=&quot;container-full&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col s6 medicines&quot;]/div[@class=&quot;medicines-top&quot;]/nav[@class=&quot;search col m5 z-depth-0&quot;]/div[@class=&quot;nav-wrapper&quot;]/form[1]/div[@class=&quot;input-field&quot;]/div[@class=&quot;search-results-item&quot;]/a[1]</value>
      <webElementGuid>7e33a057-faec-46fb-82d8-a183fcf12d77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home']/div/div/div/div/nav/div/form/div/div/a</value>
      <webElementGuid>670d3071-d41e-42e7-b423-e2b01250bdde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Transaksi : 18055#T1-111EY0018055F'])[1]/following::a[1]</value>
      <webElementGuid>3704afe7-0e9e-4e24-909f-4482230a7bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='not_interested'])[1]/following::a[1]</value>
      <webElementGuid>ca44e12e-e3ab-4018-a7e6-58d281059558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FLUIMUCIL 200MG SACH@30 (Stok: 92,']/parent::*</value>
      <webElementGuid>1aa71483-04db-432d-8009-ab3deea71302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/a</value>
      <webElementGuid>baa63664-a0d5-4848-8940-f108eeefc602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'FLUIMUCIL 200MG SACH@30 (Stok: 92, stock lock: 0)' or . = 'FLUIMUCIL 200MG SACH@30 (Stok: 92, stock lock: 0)')]</value>
      <webElementGuid>4298e6dd-abd5-4657-975f-97c56c7abdfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
