<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LOGIN</name>
   <tag></tag>
   <elementGuidId>8b933feb-1348-486e-a070-5dd504d9b586</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='report-cashier']/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.row > a.waves-effect.waves-light.btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2423e14d-20a9-4bdd-85e7-ffa52be22205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login/user</value>
      <webElementGuid>d392aaf9-218d-4d4a-bb8c-dfc24be23f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>waves-effect waves-light btn</value>
      <webElementGuid>81fd1ec1-271c-44c1-8394-e72c82fa349c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGIN</value>
      <webElementGuid>b28028a7-050b-4372-9d91-ca59169464a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report-cashier&quot;)/div[@class=&quot;container-full&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;row&quot;]/a[@class=&quot;waves-effect waves-light btn&quot;]</value>
      <webElementGuid>f9e276b9-ac14-459e-84a0-57eaebe728f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='report-cashier']/div/div/div/a</value>
      <webElementGuid>ea7b42b5-ddc0-4a11-8dd3-37ec741e97e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LOGIN')]</value>
      <webElementGuid>d2461af8-a8a4-4210-ab78-af13ff9da352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp308.861'])[1]/following::a[1]</value>
      <webElementGuid>66596515-fa36-4f40-9698-c499a945ea45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selisih nilai setoran'])[1]/following::a[1]</value>
      <webElementGuid>cc3f9e40-00f3-4139-9bb3-b83cb618b353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGIN']/parent::*</value>
      <webElementGuid>ffa47303-dc68-4984-861b-6f0ed4def351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/login/user')]</value>
      <webElementGuid>2fe4ce36-8b4c-4146-9926-ed3544a1b942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a</value>
      <webElementGuid>cbf0da9c-1488-4169-8cb8-95beaf6048f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/login/user' and (text() = 'LOGIN' or . = 'LOGIN')]</value>
      <webElementGuid>c2e05438-02b8-4581-85e0-f51015d92c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp0'])[13]/following::a[1]</value>
      <webElementGuid>32b7187c-4bdb-43d6-a186-f8b4f050c4cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='- Rp15.083'])[1]/following::a[1]</value>
      <webElementGuid>842a8c39-2cdf-4522-9e97-892c7b03d07d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
