<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PANADOL EXTRA  100 TAB (Stok 9941, stock lock 8)</name>
   <tag></tag>
   <elementGuidId>36b13f1c-4946-4e2e-acec-71740ff8fe1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home']/div/div/div/div/nav/div/form/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.search-results-item > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5db2a2d1-400f-401c-934d-b8843c0b6c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-id-search</name>
      <type>Main</type>
      <value>140207053</value>
      <webElementGuid>f47ae1f5-23c4-4273-bd41-ee40fa71a51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANADOL EXTRA @ 100 TAB (Stok: 9941, stock lock: 8)</value>
      <webElementGuid>6551ccb1-8717-42df-9f14-cd6547478a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/div[@class=&quot;container-full&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col s6 medicines&quot;]/div[@class=&quot;medicines-top&quot;]/nav[@class=&quot;search col m5 z-depth-0&quot;]/div[@class=&quot;nav-wrapper&quot;]/form[1]/div[@class=&quot;input-field&quot;]/div[@class=&quot;search-results-item&quot;]/a[1]</value>
      <webElementGuid>7bf2da6b-8c46-4f8d-a71b-9842db790155</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home']/div/div/div/div/nav/div/form/div/div/a</value>
      <webElementGuid>23a6e8a1-5e06-4834-8e34-eb02e9010f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Transaksi : 18084#T1-111EY0018084E'])[1]/following::a[1]</value>
      <webElementGuid>53914831-c07b-4918-931f-bfd881014a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='not_interested'])[1]/following::a[1]</value>
      <webElementGuid>efec1d21-de5e-452d-b0ff-374d76f430f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PANADOL EXTRA @ 100 TAB (Stok: 9941,']/parent::*</value>
      <webElementGuid>e60aef75-626f-4001-9537-ae2a2be74d77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/a</value>
      <webElementGuid>47a8437a-680e-4a66-8514-b193d0762495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'PANADOL EXTRA @ 100 TAB (Stok: 9941, stock lock: 8)' or . = 'PANADOL EXTRA @ 100 TAB (Stok: 9941, stock lock: 8)')]</value>
      <webElementGuid>0661ae96-4668-46bb-9966-25fb5436c4cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
