<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PANADOL ACTIFAST TAB8 (Stok 1000, stock lock 0)</name>
   <tag></tag>
   <elementGuidId>55ee4675-30ac-40d6-9317-54c58d54b3ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home']/div/div/div/div/nav/div/form/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.search-results-item > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e489040d-ca1f-4cff-b068-4aa45817db7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-id-search</name>
      <type>Main</type>
      <value>141667557</value>
      <webElementGuid>21df3908-e138-424e-b963-9660bbfebfc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PANADOL ACTIFAST TAB@8 (Stok: 1000, stock lock: 0)</value>
      <webElementGuid>cb8e6977-757e-46d2-a9c4-e5e329e1b399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home&quot;)/div[@class=&quot;container-full&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col s6 medicines&quot;]/div[@class=&quot;medicines-top&quot;]/nav[@class=&quot;search col m5 z-depth-0&quot;]/div[@class=&quot;nav-wrapper&quot;]/form[1]/div[@class=&quot;input-field&quot;]/div[@class=&quot;search-results-item&quot;]/a[1]</value>
      <webElementGuid>bd4ce1ac-1888-4182-9729-bb92e11f1e00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home']/div/div/div/div/nav/div/form/div/div/a</value>
      <webElementGuid>ca2b8786-5f06-4df1-b68d-1760aa28c6fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Transaksi : 18055#T1-111EY0018055F'])[1]/following::a[1]</value>
      <webElementGuid>123f874b-b236-4975-862b-4e4278404565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='not_interested'])[1]/following::a[1]</value>
      <webElementGuid>0febd6bb-063e-48dd-85cb-21bb615170c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PANADOL ACTIFAST TAB@8 (Stok: 1000,']/parent::*</value>
      <webElementGuid>b6d55c24-ad37-44aa-9b3f-05c0c38c214b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/a</value>
      <webElementGuid>6a081b31-8dfc-4625-b5ee-f3b7712bcfd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'PANADOL ACTIFAST TAB@8 (Stok: 1000, stock lock: 0)' or . = 'PANADOL ACTIFAST TAB@8 (Stok: 1000, stock lock: 0)')]</value>
      <webElementGuid>84115d61-5e45-45a5-aef0-993cdef95488</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
