<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SELESAI</name>
   <tag></tag>
   <elementGuidId>99a1695a-3ab2-4529-9ef2-94973a62670f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submit-employee']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#submit-employee</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>593385ef-a697-49c2-959c-ffeba6e56638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-employee</value>
      <webElementGuid>3295b23b-999d-4edb-8b2b-e3bd75fa3a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>waves-effect waves-green btn submit right</value>
      <webElementGuid>d9b93205-b00a-4e71-9bf5-d63c22117734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      SELESAI
      
    </value>
      <webElementGuid>0938304a-7396-4d83-8f9a-59109aed83ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit-employee&quot;)</value>
      <webElementGuid>f54af48c-7240-4cef-8f34-752892ba277c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submit-employee']</value>
      <webElementGuid>c5842c58-ad07-4683-ad8a-66c143270999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-modal']/div/div[2]/div/button</value>
      <webElementGuid>a8affae4-431e-44b4-a63c-17dc11605d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YUNI NURMAHAYATI'])[1]/following::button[1]</value>
      <webElementGuid>12132c1a-f1fd-4064-843e-683b01aa4538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TEGUH WINARKO'])[1]/following::button[1]</value>
      <webElementGuid>17f4be22-cab8-4e63-963c-0abebcee8b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'submit-employee', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>0710a857-659d-47bb-8913-e54ad9fc875c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SELESAI']/parent::*</value>
      <webElementGuid>9c1806af-16f3-4adf-a332-11f358fb7234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>e7c04708-3548-4c9e-9cee-3a636f234588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'submit-employee' and (text() = '
      SELESAI
      
    ' or . = '
      SELESAI
      
    ')]</value>
      <webElementGuid>692c6534-31da-4bb9-89fd-d0a0234b7107</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
