<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ya</name>
   <tag></tag>
   <elementGuidId>61cbca4b-b57b-4311-9f88-1289ca330b13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='edit_cashier_session_5337']/div[2]/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.waves-effect.waves-green.btn.confirm.col.s12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ddd06cdc-d5cc-470b-bede-464af25fca5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-action-scene-submit</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4514b833-96b2-4e81-95ae-b3474713f5d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>waves-effect waves-green btn confirm col s12</value>
      <webElementGuid>587841c3-79e4-4497-8000-c2090e4c7c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ya</value>
      <webElementGuid>298b53ff-71c1-4ff5-8311-7f1a64639ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_cashier_session_5337&quot;)/div[@class=&quot;modal-footer&quot;]/div[@class=&quot;row&quot;]/button[@class=&quot;waves-effect waves-green btn confirm col s12&quot;]</value>
      <webElementGuid>1d179da9-6863-46af-ac2a-56a422112ba5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5337']/div[2]/div[2]/button</value>
      <webElementGuid>03e31f4a-428b-4676-92cb-23af667d7cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Uang Setor'])[1]/following::button[1]</value>
      <webElementGuid>c2a92449-1476-4d99-8717-efadbf2ca067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah Anda yakin akan mengakhiri sesi ini?'])[1]/following::button[1]</value>
      <webElementGuid>f3c54ef9-368a-444c-abaa-b22ce1c386a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ya']/parent::*</value>
      <webElementGuid>52be72ea-630c-4000-ad0d-0d740c566c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>8bf41154-6735-45ed-90c9-eab09d297ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Ya' or . = 'Ya')]</value>
      <webElementGuid>6103c903-4f3f-4feb-ac41-64aa760ec00d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5333']/div[2]/div[2]/button</value>
      <webElementGuid>883031c3-226d-40c0-84e8-375ad2c7b3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5330']/div[2]/div[2]/button</value>
      <webElementGuid>7212ecba-3760-4235-8fe7-306d2bb74dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5326']/div[2]/div[2]/button</value>
      <webElementGuid>141b2072-6e9d-43a2-b7c0-5e8bfefe007c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5320']/div[2]/div[2]/button</value>
      <webElementGuid>d9d13b45-56c3-4f76-b140-4e045831ee4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sesi kasir sebelumnya masih aktif, silahkan tutup sesi kasir terlebih dahulu.'])[1]/following::button[1]</value>
      <webElementGuid>cb74972d-04e9-4c52-bf30-eca6166ec1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>8dc63f35-1aaa-496f-8b4e-3d8be26e43ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5317']/div[2]/div[2]/button</value>
      <webElementGuid>f10a1df5-5614-4e88-b2a9-3bc98e9643da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5313']/div[2]/div[2]/button</value>
      <webElementGuid>33e348e5-9f4e-416f-9960-06cf3b284b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5308']/div[2]/div[2]/button</value>
      <webElementGuid>adbfcd03-c2f8-4bc0-a0ea-7ecbe0f1135a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
