<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Simpan</name>
   <tag></tag>
   <elementGuidId>b1bdea45-59e8-4cee-9b36-e4b68deb7a6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-save-non-dispensed-drug']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-save-non-dispensed-drug</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee97ba37-559d-4c56-a76c-737bd84e90c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>waves-effect waves-green btn confirm</value>
      <webElementGuid>076fcd23-23f4-4708-8c47-08acb518d291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-save-non-dispensed-drug</value>
      <webElementGuid>e12a541f-854d-4031-b7b6-3c110e9b3b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>3f0a48f7-6a81-47dd-bdc2-9df331418593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-save-non-dispensed-drug&quot;)</value>
      <webElementGuid>e232f7de-f6fd-4dd5-b641-547fb15aa92f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-save-non-dispensed-drug']</value>
      <webElementGuid>4ce829ee-6901-47e3-873a-0c6cde4ff796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-non-disp']/div[2]/div/button</value>
      <webElementGuid>9bf1c26d-a25f-430b-82c8-d349ab95825b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cost Sharing'])[1]/following::button[1]</value>
      <webElementGuid>223682b3-e3d2-4e0c-a8a6-f08c01912ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catatan'])[1]/following::button[1]</value>
      <webElementGuid>bd0bab2d-6ec5-4ba9-ba86-7b0697a63856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Racikan 1'])[1]/preceding::button[1]</value>
      <webElementGuid>63329d17-6202-4640-96c3-334367ee339a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Racikan Resep'])[1]/preceding::button[1]</value>
      <webElementGuid>47cbc714-e0af-4bbd-a265-ee4c3cb6281d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>0d7c37ba-cfbb-43d5-9766-8a7eb4ca2f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-save-non-dispensed-drug' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>2c352fb2-abf2-4c69-93d2-d367337e4f33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
