<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Bayar</name>
   <tag></tag>
   <elementGuidId>c1a2506d-aca8-486d-9f78-c4873a270e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_payment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_payment</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c48ac14a-e756-4f1d-99e3-eb614cf87bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>waves-effect waves-green btn confirm</value>
      <webElementGuid>8bb8a691-270d-4b4b-9db1-e930f3daf769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_payment</value>
      <webElementGuid>a6827bd2-0232-448f-96b7-29b68736b558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Bayar
                
                </value>
      <webElementGuid>95214a73-7363-4b2e-a9de-1bd745f95b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_payment&quot;)</value>
      <webElementGuid>9b95a07e-0e63-4f06-92ce-dcb2a9c9bd66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_payment']</value>
      <webElementGuid>01c0344e-de9f-44b6-aad2-63a7c29ae893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-info-button-container']/div/div[2]/button</value>
      <webElementGuid>7dfeb17c-fbfb-481c-9d4e-58c61f691951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 8.861'])[1]/following::button[1]</value>
      <webElementGuid>e92c1388-2504-42ed-85bd-c62dce2510f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Kembalian'])[1]/following::button[1]</value>
      <webElementGuid>b73ecd5c-c327-426a-8eb5-261bec80c408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'btn_payment', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>2619cb80-b65f-4f83-b685-4f2fe9d6bf82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bayar']/parent::*</value>
      <webElementGuid>01f096aa-0396-4800-9763-ca7b8dff34d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>95dc5813-16b7-4f82-ae46-56d89d193a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_payment' and (text() = '
                Bayar
                
                ' or . = '
                Bayar
                
                ')]</value>
      <webElementGuid>002823f6-5a1e-4736-b416-c0ad93fa64b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 4.917'])[1]/following::button[1]</value>
      <webElementGuid>010bf43d-7945-403f-bb35-e586dd6c8c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 0'])[2]/following::button[1]</value>
      <webElementGuid>f127af52-c5f1-43c0-a8cc-f69553a32c9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
