<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ya</name>
   <tag></tag>
   <elementGuidId>0e943797-5a14-40a7-8ba2-65e39b764975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='edit_cashier_session_5333']/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8f8e47ce-fcb6-4106-afcf-57171dd1dc75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>5ae46a70-eb13-416f-aa5f-7a963336506b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      Ya
    </value>
      <webElementGuid>716ca439-e8a9-47c3-97ad-ddb8ab2ad924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_cashier_session_5333&quot;)/div[@class=&quot;modal-footer&quot;]/div[@class=&quot;row&quot;]</value>
      <webElementGuid>0ca00465-a92a-4087-8ca8-99e404e7656c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5333']/div[2]/div[2]</value>
      <webElementGuid>dd25b0f3-f15f-43f0-b756-03deeb50c4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah Uang Setor'])[1]/following::div[1]</value>
      <webElementGuid>7e9b786c-deb7-4d61-93c5-7e78b004b2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah Anda yakin akan mengakhiri sesi ini?'])[1]/following::div[4]</value>
      <webElementGuid>9a7a4e1f-d8e9-4fdd-b313-e8561df4601e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/form/div[2]/div[2]</value>
      <webElementGuid>76249b49-219f-4b32-8345-46bb4aaea5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
      Ya
    ' or . = '
      Ya
    ')]</value>
      <webElementGuid>e93346f9-c396-4bc0-8649-b55a9660bb50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
