<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Alumni ITBYaTidakMemberNo TeleponNama _f9d228</name>
   <tag></tag>
   <elementGuidId>97a2090e-6005-4d1b-bfe4-4bbaa5b93ef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='edit_prescription_3063']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#edit_prescription_3063</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>8ac75ad5-bcca-43c4-ae9d-c441de4fc718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit_prescription</value>
      <webElementGuid>658ee13d-e626-4a6a-a847-8f93d96c11fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edit_prescription_3063</value>
      <webElementGuid>bbd96353-e920-4c11-bf98-154019517825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>https://pos-development.buaya.dev/pos_expres/order/18101/edit_prescription2/3063?edit=true</value>
      <webElementGuid>2db755d6-96bc-48d9-87c6-d61a4ba6e185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept-charset</name>
      <type>Main</type>
      <value>UTF-8</value>
      <webElementGuid>f23afb79-91ba-4589-8c98-2ce87f9842c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>method</name>
      <type>Main</type>
      <value>post</value>
      <webElementGuid>5fc91095-fc26-4966-b3fc-57ce5c0fb1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>



Alumni ITB



Ya



Tidak








Member






 




No Telepon



Nama Lengkap



Batal
Simpan







Pilih Metode Bayar


Tunai



Kredit Resep
-pilih jaminan-
 NESTLE INDONESIA PT -NESTLE INDONESIA PT MALANG
ABDA-
ADMEDIKA PAYOR PT 2-   
ADMEDIKA PAYOR PT-
ADMEDIKA PAYOR PT- 
ADMEDIKA PAYOR PT-AIA
ADMEDIKA PAYOR PT-AIA INDIVIDU
ADMEDIKA PAYOR PT-ALLIANZ
ADMEDIKA PAYOR PT-ASTRA BUANA
ADMEDIKA PAYOR PT-ASURANSI AXA INDONESIA
ADMEDIKA PAYOR PT-AVIVA
ADMEDIKA PAYOR PT-AXA MANDIRI
ADMEDIKA PAYOR PT-BANK MANDIRI INHEALTH
ADMEDIKA PAYOR PT-BNI LIFE INSURANCE
ADMEDIKA PAYOR PT-BUKOPIN
ADMEDIKA PAYOR PT-BULOG
ADMEDIKA PAYOR PT-COMMONWEALTH LIFE
ADMEDIKA PAYOR PT-EQUITY
ADMEDIKA PAYOR PT-FWD
ADMEDIKA PAYOR PT-GENERALI
ADMEDIKA PAYOR PT-GREAT EASTERN INSURANCE
ADMEDIKA PAYOR PT-HANHWA LIFE
ADMEDIKA PAYOR PT-ICON +
ADMEDIKA PAYOR PT-INDEMNITY
ADMEDIKA PAYOR PT-INDOSURYA LIFE
ADMEDIKA PAYOR PT-INHEALTH
ADMEDIKA PAYOR PT-JIWA RECAPITAL INSURANCE
ADMEDIKA PAYOR PT-JIWA SINARMAS
ADMEDIKA PAYOR PT-KARYAWAN &amp; KELUARGA
ADMEDIKA PAYOR PT-KOPELINDO BULOG
ADMEDIKA PAYOR PT-LION SUPERINDO
ADMEDIKA PAYOR PT-MAYBANK
ADMEDIKA PAYOR PT-MEGA HEALTH
ADMEDIKA PAYOR PT-MEGA INSURANCE
ADMEDIKA PAYOR PT-MNC LIFE
ADMEDIKA PAYOR PT-NUSANTARA REGAS
ADMEDIKA PAYOR PT-OJK
ADMEDIKA PAYOR PT-PT JOB PERTAMINA
ADMEDIKA PAYOR PT-RELIANCE
ADMEDIKA PAYOR PT-SINAR MAS
ADMEDIKA PAYOR PT-SOMPO
ADMEDIKA PAYOR PT-SUN LIFE FINANCIAL
ADMEDIKA PAYOR PT-TELKOMEDIKA
ADMEDIKA PAYOR PT-TOKIO MARINE LIFE INSURANCE
ADMEDIKA PAYOR PT-TRI TUNGGAL MANDIRI
ADMEDIKA PAYOR PT-TUGU PRATAMA INDO
ADMEDIKA PAYOR PT-WANAARTHA LIFE
ADMEDIKA PAYOR PT-WIJAYA KARYA
ADMEDIKA PAYOR PT-WINTERTHUR
ANEKA TAMBANG PT-CIKOTOK
ANEKA TAMBANG PT-GEBE
ANEKA TAMBANG PT-PEGAWAI
ANEKA TAMBANG PT-PENSIUNAN
ANEKA TAMBANG PT-POMALAA
ANEKA TAMBANG PT-PONGKOR
ANEKA TAMBANG PT-YAKESPEN
ANGKASA PURA I POLIKLINIK-DEFAULT
ANGKASA PURA I PT-
ANGKASA PURA II PT-
ANGKASA PURA II PT-AIRNAV
ANGKASA PURA II PT-CABANG
ANGKASA PURA II PT-DIREKSI
ANGKASA PURA II PT-GADAR MEDIK
ANGKASA PURA II PT-HALIM
ANGKASA PURA II PT-KELUARGA
ANGKASA PURA II PT-LUAR KOTA
ANGKASA PURA II PT-PENSIUNAN
ANGKASA PURA II PT-POLIKLINIK
APOTEK - APOTEK- (Non Aktif)
APOTEK KF KEMANGGISAN
APOTEK PALU- (Non Aktif)
AQUA GOLDEN MISSISSIPI PT-AQUA KONSINYASI
AQUA GOLDEN MISSISSIPI PT-ENGGROS PO
ASKES-ASKES MALANG
ASKES-ASKES RAWAT INAP
ASKES-ASKES RAWAT JALAN
ASKES-DR KELUARGA
ASKES-DR KELUARGA KOM
ASKES-DR KELUARGA SOS
ASKES-DR. PURWANINGSIH
ASKES-KOMERSIAL BATAM
ASKES-KRONIS
ASKES-NON DPHO
ASKES-RJTP
ASKES-SOSIAL INAP
ASKES-SUKARELA
ASKES-SUKARELA RW. INAP
ASKES-SUKARELA RW. JALAN
ASKES-WAJIB RW. INAP
ASKES-WAJIB RW. JALAN
ASTRA GRAPHIA-
ASURANSI ADIRA DINAMIKA P-
ASURANSI AXA INDONESIA PT
ASURANSI BINTANG PT
ASURANSI CENTRAL ASIA PT-
ASURANSI JASA INDONESIA P-
ASURANSI JIWA CENTRAL ASI-
ASURANSI JIWA GENERALI IN-
ASURANSI JIWA INHEALTH IN-
ASURANSI JIWA INHEALTH INDONESIA PT-INHEALTH FEE FOR SERVICE
ASURANSI JIWA INHEALTH INDONESIA PT-INHEALTH INDEMNITY
ASURANSI JIWA INHEALTH INDONESIA PT-INHEALTH KAPITASI
ASURANSI JIWA INHEALTH INDONESIA PT-INHEALTH KLINIK
ASURANSI JIWA INHEALTH INDONESIA PT-INHEALTH RUJUK BALIK
ASURANSI JIWA JIWASRAYA P
ASURANSI JIWA SINAR MAS M-
ASURANSI JIWA TUGU MANDIR-
ASURANSI MITRA MAPARYA PT
ASURANSI SINAR MAS PT-
ASURANSI UMUM BUMIPUTERAM-
AVRIST ASSURANCE PT-AVRIST ASSURANCE WIL C
BADAN PEMERIKSA KEUANGAN-
BALAI PENGOBATAN WEST JAV-
BANK MANDIRI-DEPOK
BANK MANDIRI-MANADO
BANK MANDIRI-PALU
BANK MANDIRI-SEMARANG
BANK MANDIRI-TASIKMALAYA OTISTA
BANK MANDIRI-YOGYAKARTA
BNI 46 LIFE INSURANCE PT-
BNI 46 LIFE INSURANCE PT-BNI 46 LIFE INSURANCE MC,JAYA1
BON KARYAWAN KFA-
BON KARYAWAN KFA-BON KARYAWAN KFA MALANG
BON PENSIUNAN KF
BPJS KAPITASI BOGOR-
BPJS KAPITASI BOGOR-TEST
BPJS KAPITASI JAYA 1-
BPJS KAPITASI JAYA 2-Rawat Jalan Unit Bisnis Jaya 2
BPJS KAPITASI-
BPJS KAPITASI-BPJS KAPITASI BANDUNG
BPJS KESEHATAN BANDUNG-PASIEN RUJUK BALIK
BPJS KESEHATAN BOGOR-ALKES
BPJS KESEHATAN BOGOR-IGD
BPJS KESEHATAN BOGOR-OPTIK
BPJS KESEHATAN BOGOR-PASIEN KRONIS
BPJS KESEHATAN BOGOR-PASIEN RUJUK BALIK (Non Aktif)
BPJS KESEHATAN BOGOR-PROLANIS
BPJS KESEHATAN BOGOR-RAWAT INAP
BPJS KESEHATAN BOGOR-RAWAT JALAN
BPJS KESEHATAN CIREBON-PASIEN RUJUK BALIK (Non Aktif)
BPJS KESEHATAN JAYA 1
BPJS KESEHATAN JAYA 1-RAWAT INAP
BPJS KESEHATAN JAYA 1-RAWAT JALAN
BPJS KESEHATAN JAYA 2-
BPJS KESEHATAN JAYA 2-PASIEN KRONIS
BPJS KESEHATAN JAYA 2-PASIEN RUJUK BALIK
BPJS KESEHATAN JAYA 2-RAWAT JALAN
BPJS KESEHATAN JAYA 2-kelas 1
BPJS KESEHATAN JAYA 2-kelas 2
BPJS RUJUK BALIK-DEFAULT
BPJS Rawat Inap-INSTALASI FARMASI RSCM - SAS
BPJS Rawat Jalan-
BPKP PUSAT-
BUKIT ASAM PT-BUKIT ASAM - KANTOR TAMBANG
BUKIT ASAM PT-BUKIT ASAM - PENSIUNAN
BUKIT ASAM PT-BUKIT ASAM - TAMBANG
CONOCOPHILLIPS INDONESIA
DAMRI-
DEPOT LOGISTIK JAYA
DIKLUSEPORA (PDK)
DINAS NAKERTRANS SULTENG
DOKTER &amp; KARYAWAN RSAB
DOKTER - DOKTER-
DOKTER INHOUSE-
DOVER CHEMICAL PT-
DR KO KING TJOEN-
DR ROH PRABOWO-
DR SUPRAYITNO-
ENGGROS SWASTA-
GARUDA INDONESIA PT-JASA MEDICA
GARUDA INDONESIA PT-JPK-I MANADO
GARUDA INDONESIA PT-SENTRA MEDIKA
GARUDA INDONESIA PT-SENTRA MEDIKA -AEROWISATA
GARUDA INDONESIA PT-SENTRA MEDIKA JPK I
GARUDA INDONESIA PT-SENTRA MEDIKA JPK II
GARUDA INDONESIA PT-SENTRA MEDIKA JPK III
GELORA BUNG KARNO (100%)
GEO DIPA ENERGI PT
GEO DIPA ENERGI PT
GOODYEAR INDONESIA-
GRAMEDIA PT-CORPORATE ADVERTISING
GRAMEDIA PT-CORPORATE CIRCULATION
GRAMEDIA PT-CORPORATE COMMUNICATION
GRAMEDIA PT-CORPORATE CONTROLLER
GRAMEDIA PT-CORPORATE FACILITY MANAGEMEN
GRAMEDIA PT-CORPORATE HUMAN RESOURCES
GRAMEDIA PT-GROUP OF BOOKS PUBLISHING
GRAMEDIA PT-GROUP OF MAGAZINE
GRAMEDIA PT-GROUP OF PRINTING
GRAMEDIA PT-KOMPAS
GRAMEDIA PT-KONTAN
GRAMEDIA PT-MULTI MEDIA (MMSP)
GRAMEDIA PT-PERCETAKAN
GRAMEDIA PT-TRANSITO ADIMANJATI
GREAT EASTERN INSURANCE P
HANHWA LIFE
IOM
JASA RAHARJA PT-
JIEP PT
JPK DASAR RAWAT JALAN(DUK
KANWIL DIREKTORAT JENDERA
KBN PRIOK- (Non Aktif)
KEHUTANAN PHPA
KEHUTANAN PHPA POLIKLINIK
KF HOLDING AFILIASI (NON AKTIF)-PEMASARAN
KF HOLDING AFILIASI PROMOSI(NON AKTIF)
KF HOLDING AFILIASI(NON AKTIF)
KF PLANT JAKARTA
KF UNIT LOGISTIK SENTRAL
KFA PUSAT
KFTD AFILIASI-KFTD ACEH
KFTD AFILIASI-KFTD UNIT BISNIS PUSAT
KIMIA FARMA DIAGNOSTIK-
KLINIK BUKIT CIRENDEU
KLINIK MEDIKA BINA SEJAHT
KPB--
KPB-HN TU
KPB-NS SAWIT
KPB-NS TEH
KPB-NS TU
KPB-ST ANALISA PASAR
KPB-ST GULA
KPB-ST SAWIT
KPB-ST SPI
KPB-ST TEH
KPB-ST TU
KPP PENANAMAN MODAL ASING
KPP PRATAMA MATRAMAN-
KPPN JAKARTA-
KPPN PASAR REBO
KREDIT LAIN-LAIN (RELASI)-
LEMBAGA PENDIDIKAN PERKEB
MAHKAMAH AGUNG-
MAKO ARMABAR (Non Aktif)
MEGA ELTRA PT
MITRA KELUARGA PIRANTI SE-
Medevo-PLN KANTOR PUSAT TANGERANG
NAYAKA ERA HUSADA PT-JKP
NAYAKA ERA HUSADA PT-JPK PLUS
NAYAKA ERA HUSADA PT-JPK PLUS KELAS 1
NAYAKA ERA HUSADA PT-KELAS 2
NAYAKA ERA HUSADA PT-NAYAKA ERA HUSADA, BANDUNG
OLYMPIC GARMENT PT
OWLEXA INDONESIA-DEFAULT
PAM JAYA PT
PASPAMPRES
PELNI PT-
PERFETTI VAN MELLE INDONE-
PERPUSTAKAAN NASIONAL-
PERTAMEDIKA MEDICAL CENTR-
PERUM LPPNPI-
PERUSAHAAN SWASTA-
PETROSEA PT
PLN (PERSERO) JASA SERTIF
PLN (PERSERO) WILAYAH KALTIM, PT-DEFAULT
PLN AJ GAMBIR PENSIUNAN
PLN AJ GAMBIR-
PLN AJ JATINEGARA
PLN AJ KEBAYORAN
PLN AJ KEBAYORAN PENSIUNA
PLN AJ KRAMAT JATI
PLN AJ KRAMATJATI PENSIUN
PLN AJ TANGERANG
PLN AP BANDENGAN
PLN AP BINTARO
PLN AP BULUNGAN
PLN AP BULUNGAN PENSIUNAN
PLN AP CEMPAKA PUTIH
PLN AP CENGKARENG
PLN AP CIKOKOL
PLN AP CIKOKOL PENSIUNAN
PLN AP CIKUPA
PLN AP CILEDUK
PLN AP CILEDUK PENSIUNAN
PLN AP CINERE
PLN AP CIPUTAT
PLN AP CIRACAS
PLN AP CONDET
PLN AP GAMBIR (Non Aktif)
PLN AP GROGOL
PLN AP GUNUNG SAHARI
PLN AP JATINEGARA
PLN AP KALIDERES
PLN AP KALIMALANG
PLN AP KEBAYORAN
PLN AP KEBON JERUK
PLN AP KOTA
PLN AP KRAMAT JATI
PLN AP LENTENG AGUNG
PLN AP MAMPANG
PLN AP MARUNDA
PLN AP MENTENG
PLN AP PAMULANG
PLN AP PASAR MINGGU
PLN AP PONDOK GEDE
PLN AP PONDOK KOPI
PLN AP RAWAMANGUN
PLN AP SERPONG
PLN AP SUNTER PENSIUNAN
PLN AP TANGERANG-
PLN AP TANJUNG PRIOK
PLN APD SEMARANG-
PLN BANGKA BELITUNG-DEFAULT
PLN BENGKEL KLENDER PEGAW
PLN BENGKEL KLENDER PENSI
PLN CAB I WIL. V
PLN CAB II A.YANI
PLN CAB III KAPUAS
PLN DIST CABANG BOGOR
PLN DIST JABAR &amp; BANTEN-
PLN DIST JATENG &amp; DIY-
PLN DIST JATENG &amp; DIY-
PLN DIST JATIM
PLN DIST JATIM-PLN DIST JATIM MALANG
PLN DIST JAWA BARAT (KARA-
PLN DIST JAYA &amp; TANGERANG-Unit Bisnis Jaya 2
PLN DIST LAMPUNG-
PLN JASA SERTIFIKASI-
PLN JASDIK PENSIUNAN
PLN JASDIK U JAKARTA
PLN JASDIK UDIKLAT-
PLN JASDIK WIJAYA
PLN JTK SATUAN BKU
PLN JTK SATUAN JTK
PLN JTK SATUAN PNS
PLN K.DISTRIBUSI PENSIUNA-
PLN KANTOR DISTRIBUSI-
PLN KANTOR PUSAT-
PLN KANTOR PUSAT-PLN KANTOR PUSAT SURABAYA
PLN KANTOR PUSAT-PLN KANTOR PUSAT, JAYA I
PLN KANTOR PUSAT-PLN KANTOR PUSAT, PEKALONGAN
PLN KANTOR PUSAT-PLN KANTOR PUSAT-BEKASI
PLN KIT TJB-DEFAULT
PLN LITBANG KETENAGA LIST
PLN LITBANG SATUAN BKIT
PLN LITBANG SATUAN BMPS
PLN LITBANG SATUAN BSAK
PLN LITBANG SATUAN BTND
PLN LITBANG SATUAN GM LIT
PLN P2B AREA PENGATUR BEB-
PLN P3B JAWA BALI-
PLN P3B UBS PENSIUNAN
PLN P3B UBS-
PLN P3B UPBC-
PLN P3B UPT-
PLN P3B-PLN P3B MALANG
PLN PEMBANGKIT TANJUNG JA
PLN PJB I-
PLN PJB II MUARA KARANG
PLN PJB PENSIUNAN-PLN PJB PENSIUNAN MALANG
PLN PROKITRING
PLN PROYEK JARINGAN (JATE-
PLN PROYEK JARINGAN TIMUR-
PLN PT
PLN PUSAT BAGIAN SPI
PLN PUSAT PEGAWAI-
PLN PUSAT PEL ENGINEERING-
PLN PUSAT PENSIUNAN
PLN PUSAT POLIKLINIK
PLN PUSDIKLAT-
PLN PUSHARLIS-
PLN PUSLITBANG-
PLN SEKTOR P3B BOGOR
PLN SEKTOR PEMBANGKIT-
PLN SEKTOR PENSIUNAN BOGO-
PLN SEKTOR RANGKAS BOGOR
PLN SEKTOR UJT BOGOR
PLN SEKTOR UPT BOGOR
PLN TRANSMISI JAWA BAG BA-
PLN TRANSMISI JAWA BAG TE-
PLN TRANSMISI JAWA BAG TI
PLN TRANSMISI SUMBAR-
PLN UDIKLAT PENSIUNAN
PLN UDIKLAT SISWA
PLN UDIKLAT-
PLN UIP SULAWESI MALUKU P
PLN UJT KELISTRIKAN
PLN UJT PULO GADUNG
PLN UNIT INSTALASI PEMBAN-
PLN UNIT KANTOR DISTRIBUS
PLN UNIT PENGATUR DISTRIB
PLN UPT BANDA ACEH-
PLN WILAYAH KALSEL &amp; KALT-
PLN WILAYAH NTB
PLN WILAYAH PAPUA-
PLN WILAYAH SULSELBAR-DEFAULT
PLN WILAYAH SULUTTENGGO-DEFAULT
PLN WILAYAH SUMBAR PEGAWA
PLN WILAYAH SUMBAR-DEFAULT
PLN WILAYAH SUMUT-DEFAULT
PLN WILAYAH V PONTIANAK
POLIKLINIK BEA &amp; CUKAI (T
POLIKLINIK CENDANA-
POLIKLINIK INSTANSI-
POLIKLINIK SWASTA-
POLIKLINIK TAMAN SAFARI-
POS INDONESIA PT-CABANG BAGINDO AZIZ KHAN (Non Aktif)
POS INDONESIA PT-KANWIL
POS INDONESIA PT-PENSIUNAN
POS INDONESIA PT-WILAYAH KHATIB SULAIMAN
PPATK-
PT. KIMIA FARMA DIAGNOSTIKA-DEFAULT
PT. PERTAMINA HULU ENERGI (PHE)-DEFAULT
PUSRI PT
RESEP PEGAWAI SENDIRI-DEFAULT
RS DR H MARZOEKI MAHDI-
RS GATOT SUBROTO-
RS HARAPAN KITA
RS HERMINA TANGERANG-
RS HERMINA-
RS PEMERINTAH-
RS PERTAMINA JAYA-
RS SWASTA-
RS TEBET-
RSCM-BPJS ALAT DENGAR RSCM
RSCM-BPJS KRONIS RSCM
RSCM-BPJS R. INAP RSCM
RSCM-BPJS R. JALAN RSCM
RSCM-DIREKSI RSCM
RSCM-INSTALASI FARMASI RSCM - CITO
RSCM-INSTALASI FARMASI RSCM - OBAT
RSCM-INSTALASI FARMASI RSCM - RESEP
RSCM-JAMKESDA RAWAT JALAN RSCM
RSCM-KEMOTERAPI RSCM
RSCM-UNIT JAMINAN RSCM ( UPPJ )
RSCM-UNIT KARYAWAN RSCM JAKARTA
RST CIREMAI-
RSUD TARAKAN
SAHID SAHIRMAN MEMORIAL HOSPITAL-ASS RAWAT JALAN
SAHID SAHIRMAN MEMORIAL HOSPITAL-ASS RI KELAS A
SAHID SAHIRMAN MEMORIAL HOSPITAL-ASS RI KELAS B
SAHID SAHIRMAN MEMORIAL HOSPITAL-ASS RI SUITE
SAHID SAHIRMAN MEMORIAL HOSPITAL-ASS RI VIP
SAHID SAHIRMAN MEMORIAL HOSPITAL-BHP
SAHID SAHIRMAN MEMORIAL HOSPITAL-BPJS KHEMO
SAHID SAHIRMAN MEMORIAL HOSPITAL-BPJS KRONIS
SAHID SAHIRMAN MEMORIAL HOSPITAL-BPJS RW INAP
SAHID SAHIRMAN MEMORIAL HOSPITAL-BPJS RW JALAN
SAHID SAHIRMAN MEMORIAL HOSPITAL-ICCU
SAHID SAHIRMAN MEMORIAL HOSPITAL-ICU
SAHID SAHIRMAN MEMORIAL HOSPITAL-IGD
SAHID SAHIRMAN MEMORIAL HOSPITAL-RI KELAS A
SAHID SAHIRMAN MEMORIAL HOSPITAL-RI KELAS B
SAHID SAHIRMAN MEMORIAL HOSPITAL-RI KELAS SUITE
SAHID SAHIRMAN MEMORIAL HOSPITAL-RI KELAS VIP
SAHID SAHIRMAN MEMORIAL HOSPITAL-SAHID GROUP DIREKSI-KOMISARIS
SETIAJAYA MOBILINDO PT-
SHARP YASONTA PT
SHELF DRILLING PT
SIAPDOK-
STAFF WAPRES-
STAR ENERGY PT
SUMBER CIPTA MULTINIAGA P-
SWAKELOLA KESEHATAN KFA-
SYNGENTA PT-
TAMAN MINI INDONESIA INDA-
TELKOM PT JAKARTA
TELKOM PT-
TELKOMEDIKA PT-
TEUKU UMAR POLIKLINIK-POLIKLINIK II
TEUKU UMAR POLIKLINIK-POLIKLINIK III
TEUKU UMAR POLIKLINIK-POLIKLINIK IV
TIRTA INVESTAMA PT-
TIRTA INVESTAMA PT-BOGOR
TIRTA INVESTAMA PT-CIANJUR
TIRTA INVESTAMA PT-CIBINONG
TIRTA INVESTAMA PT-CILEGON
TIRTA INVESTAMA PT-CIPUTAT
TIRTA INVESTAMA PT-CITEUREUP
TIRTA INVESTAMA PT-CYBER
TIRTA INVESTAMA PT-DEPO
TIRTA INVESTAMA PT-DEPO (DR LUAR)
TIRTA INVESTAMA PT-DEPO (KLINIK)
TIRTA INVESTAMA PT-DEPO MANAGER
TIRTA INVESTAMA PT-DIREKTUR
TIRTA INVESTAMA PT-DISTRIBUSI
TIRTA INVESTAMA PT-ENGGRO (PO)
TIRTA INVESTAMA PT-ENGROS/SUBANG
TIRTA INVESTAMA PT-HEAD OFFICE
TIRTA INVESTAMA PT-HO DIREKTUR
TIRTA INVESTAMA PT-HO MANAGER
TIRTA INVESTAMA PT-KEBON C
TIRTA INVESTAMA PT-KEMBANGAN
TIRTA INVESTAMA PT-PABRIK
TIRTA INVESTAMA PT-PABRIK (DR LUAR)
TIRTA INVESTAMA PT-PABRIK (KLINIK)
TIRTA INVESTAMA PT-PLT HO
TIRTA INVESTAMA PT-POLANHARJO
TIRTA INVESTAMA PT-POLI
TIRTA INVESTAMA PT-POLI PANDAAN
TIRTA INVESTAMA PT-PULO KAMBING
TIRTA INVESTAMA PT-R/ BANDUNG (Non Aktif)
TIRTA INVESTAMA PT-R/SUBANG (Non Aktif)
TIRTA INVESTAMA PT-RAWA DOMBA
TIRTA INVESTAMA PT-SALES &amp; DISTRIBUSI
TIRTA INVESTAMA PT-SUPPLY CHAIN
TIRTA INVESTAMA PT-SURABAYA
TIRTA INVESTAMA PT-SURAKARTA
TIRTA INVESTAMA PT-WONOSOBO
TIRTA INVESTAMA PT-YOGYAKARTA
TUNAI
TUNAI
TUNAI-
TUNAI-KHUSUS
TUNAI-SINAR MAS
TUNAI-TAMBAH BAYAR
TUNGGAL IDAMAN ABADI PT-
WISMA NEGARA-
YAMAHA INDONESIA MOTOR MF-
YAYASAN DARUL HIKAM
YAYASAN GINJAL DIATRANS I
YKKBI- (Non Aktif)
YKKBI-YKKBI, DEPOK
YKP BANK BJB-YKP BANK BJB-AVP VP
YKP BANK BJB-YKP BANK BJB-Off SM
YKP BANK BJB-YKP BANK BJB-STAFF
YKP BANK BJB-YKP BANK BJB-SVP SEVP
YKP OJK-ADMEDIKA PAYOR PT- 






Nama Pasien*

Nama pasien harus diisi


Nomor Telepon*

Nomor telepon harus diisi


Alamat Pasien*

Alamat pasien harus diisi




Tanggal Lahir



NIK





Dokter*






Dokter harus diisi


PPK Asal*






PPK asal harus diisi


Poli*






Poli harus diisi


Alamat Dokter Praktik*

Alamat dokter harus diisi




    .tosca {
        color: #9e9e9e;
        text-transform: capitalize;
    }


      
        
          Nomor Kartu
          
            Cari PesertaCari Peserta
        
      


    
        
            Nama Peserta*
            
        

        
        
        
        
                    
                        
                            
    No. resep*

    




  Peentar.executeLater(function(){
  Peentar.Materialize.refreshForm($('form'));
  var poly_url = $('.poly_select2').data('url');
  $('.poly_select2').select2({
    minimumInputLength: 3,
    ajax: {
      dataType: 'json',
      delay: 1000,
      url: poly_url,
      data: function (params) {
        var query = {
          q: params.term
        };
        return query;
      },
      processResults: function (data) {
        if (data.error){
          Materialize.toast(&quot;Koneksi Bermasalah&quot;, 3000);
          return false;
        }
        return {
          results: data.poly
        };
      },
    },
  });

  $('.poly_select2').on('select2:select', function (e) {

          $('#poly').val(e.params.data.text);

  });

})


                        
                    
                        
                            
    Npp*

    




  Peentar.executeLater(function(){
  Peentar.Materialize.refreshForm($('form'));
  var poly_url = $('.poly_select2').data('url');
  $('.poly_select2').select2({
    minimumInputLength: 3,
    ajax: {
      dataType: 'json',
      delay: 1000,
      url: poly_url,
      data: function (params) {
        var query = {
          q: params.term
        };
        return query;
      },
      processResults: function (data) {
        if (data.error){
          Materialize.toast(&quot;Koneksi Bermasalah&quot;, 3000);
          return false;
        }
        return {
          results: data.poly
        };
      },
    },
  });

  $('.poly_select2').on('select2:select', function (e) {

          $('#poly').val(e.params.data.text);

  });

})


                        
                    
                        
                            
    Nama_pasien*

    




  Peentar.executeLater(function(){
  Peentar.Materialize.refreshForm($('form'));
  var poly_url = $('.poly_select2').data('url');
  $('.poly_select2').select2({
    minimumInputLength: 3,
    ajax: {
      dataType: 'json',
      delay: 1000,
      url: poly_url,
      data: function (params) {
        var query = {
          q: params.term
        };
        return query;
      },
      processResults: function (data) {
        if (data.error){
          Materialize.toast(&quot;Koneksi Bermasalah&quot;, 3000);
          return false;
        }
        return {
          results: data.poly
        };
      },
    },
  });

  $('.poly_select2').on('select2:select', function (e) {

          $('#poly').val(e.params.data.text);

  });

})


                        
                    
                        
                            
    Nama obat*

    




  Peentar.executeLater(function(){
  Peentar.Materialize.refreshForm($('form'));
  var poly_url = $('.poly_select2').data('url');
  $('.poly_select2').select2({
    minimumInputLength: 3,
    ajax: {
      dataType: 'json',
      delay: 1000,
      url: poly_url,
      data: function (params) {
        var query = {
          q: params.term
        };
        return query;
      },
      processResults: function (data) {
        if (data.error){
          Materialize.toast(&quot;Koneksi Bermasalah&quot;, 3000);
          return false;
        }
        return {
          results: data.poly
        };
      },
    },
  });

  $('.poly_select2').on('select2:select', function (e) {

          $('#poly').val(e.params.data.text);

  });

})


                        
                    
                        
                            

TANGGAL RESEP




                        
       
 








  $(document).ready(function() {
      Peentar.datePicker(&quot;.datepicker&quot;);
  });







Jenis Resep



Resep Obat



Resep Optik










Obat Non-Racik

Obat Racik





Nama Obat







Item Penjamin






Jumlah



Harga Total (Rp)




Stok



Satuan



Harga Satuan (Rp)



Jumlah Resep



Jumlah Ambil



Harga (Rp)



Signa 1



Signa 2



JHO



Catatan




Cost Sharing




















Simpan









Racikan 1
KAPSUL
PUYER
SALEP
LARUTAN LUAR
LARUTAN DALAM
SUPPOSITORIA
BEDAK


Jumlah Racikan Resep




Jumlah Ambil Resep




Signa 1



Signa 2



JHO



Embalase (Rp)




Catatan




+ Obat









Nama Obat





delete



Item Penjamin





Jumlah




Harga Total (Rp)





Stok



Satuan




Harga Satuan (Rp)




Kekuatan Obat



Dosis Resep



Jumlah Resep




Jumlah Ambil




Harga (Rp)




Cost Sharing




SIMPAN



  function validateDecimal(e) {
    var t = e.value;
    e.value = (t.indexOf(&quot;.&quot;) >= 0) ? (t.substr(0, t.indexOf(&quot;.&quot;)) + t.substr(t.indexOf(&quot;.&quot;), 3)) : t;
  }








Nama Item






Stok



Kuantitas



Satuan



Harga (Rp)



Harga Total (Rp)

















Simpan








Daftar Produk


Preview Resep




  
    


    
        
        
        Belum memilih obat
    

  


  Total Harga Resep:
  Rp0




Batal


Lanjutkan



</value>
      <webElementGuid>813b17d8-dc27-4967-a23b-04d330dec36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_prescription_3063&quot;)</value>
      <webElementGuid>92c2ad9e-2f08-4ac6-b85b-c41290b659f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='edit_prescription_3063']</value>
      <webElementGuid>5b6849fa-25b1-4bd6-a5aa-38ef60768c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='not_interested'])[1]/following::form[1]</value>
      <webElementGuid>b6cf8e26-dd07-4038-9ebf-031a53082a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan'])[1]/following::form[1]</value>
      <webElementGuid>ed2ce5ee-5ecd-4e80-a9b7-7ed18b00e685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>b407b7ea-6c8d-4a20-9446-81449e744fec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'edit_prescription_3063' and (text() = concat(&quot;



Alumni ITB



Ya



Tidak








Member






 




No Telepon



Nama Lengkap



Batal
Simpan







Pilih Metode Bayar


Tunai



Kredit Resep
-pilih jaminan-
 NESTLE INDONESIA PT -NESTLE INDONESIA PT MALANG
ABDA-
ADMEDIKA PAYOR PT 2-   
ADMEDIKA PAYOR PT-
ADMEDIKA PAYOR PT- 
ADMEDIKA PAYOR PT-AIA
ADMEDIKA PAYOR PT-AIA INDIVIDU
ADMEDIKA PAYOR PT-ALLIANZ
ADMEDIKA PAYOR PT-ASTRA BUANA
ADMEDIKA PAYOR PT-ASURANSI AXA INDONESIA
ADMEDIKA PAYOR PT-AVIVA
ADMEDIKA PAYOR PT-AXA MANDIRI
ADMEDIKA PAYOR PT-BANK MANDIRI INHEALTH
ADMEDIKA PAYOR PT-BNI LIFE INSURANCE
ADMEDIKA PAYOR PT-BUKOPIN
ADMEDIKA PAYOR PT-BULOG
ADMEDIKA PAYOR PT-COMMONWEALTH LIFE
ADMEDIKA PAYOR PT-EQUITY
ADMEDIKA PAYOR PT-FWD
ADMEDIKA PAYOR PT-GENERALI
ADMEDIKA PAYOR PT-GREAT EASTERN INSURANCE
ADMEDIKA PAYOR PT-HANHWA LIFE
ADMEDIKA PAYOR PT-ICON +
ADMEDIKA PAYOR PT-INDEMNITY
ADMEDIKA PAYOR PT-INDOSURYA LIFE
ADMEDIKA PAYOR PT-INHEALTH
ADMEDIKA PAYOR PT-JIWA RECAPITAL INSURANCE
ADMEDIKA PAYOR PT-JIWA SINARMAS
ADMEDIKA PAYOR PT-KARYAWAN &amp; KELUARGA
ADMEDIKA PAYOR PT-KOPELINDO BULOG
ADMEDIKA PAYOR PT-LION SUPERINDO
ADMEDIKA PAYOR PT-MAYBANK
ADMEDIKA PAYOR PT-MEGA HEALTH
ADMEDIKA PAYOR PT-MEGA INSURANCE
ADMEDIKA PAYOR PT-MNC LIFE
ADMEDIKA PAYOR PT-NUSANTARA REGAS
ADMEDIKA PAYOR PT-OJK
ADMEDIKA PAYOR PT-PT JOB PERTAMINA
ADMEDIKA PAYOR PT-RELIANCE
ADMEDIKA PAYOR PT-SINAR MAS
ADMEDIKA PAYOR PT-SOMPO
ADMEDIKA PAYOR PT-SUN LIFE FINANCIAL
ADMEDIKA PAYOR PT-TELKOMEDIKA
ADMEDIKA PAYOR PT-TOKIO MARINE LIFE INSURANCE
ADMEDIKA PAYOR PT-TRI TUNGGAL MANDIRI
ADMEDIKA PAYOR PT-TUGU PRATAMA INDO
ADMEDIKA PAYOR PT-WANAARTHA LIFE
ADMEDIKA PAYOR PT-WIJAYA KARYA
ADMEDIKA PAYOR PT-WINTERTHUR
ANEKA TAMBANG PT-CIKOTOK
ANEKA TAMBANG PT-GEBE
ANEKA TAMBANG PT-PEGAWAI
ANEKA TAMBANG PT-PENSIUNAN
ANEKA TAMBANG PT-POMALAA
ANEKA TAMBANG PT-PONGKOR
ANEKA TAMBANG PT-YAKESPEN
ANGKASA PURA I POLIKLINIK-DEFAULT
ANGKASA PURA I PT-
ANGKASA PURA II PT-
ANGKASA PURA II PT-AIRNAV
ANGKASA PURA II PT-CABANG
ANGKASA PURA II PT-DIREKSI
ANGKASA PURA II PT-GADAR MEDIK
ANGKASA PURA II PT-HALIM
ANGKASA PURA II PT-KELUARGA
ANGKASA PURA II PT-LUAR KOTA
ANGKASA PURA II PT-PENSIUNAN
ANGKASA PURA II PT-POLIKLINIK
APOTEK - APOTEK- (Non Aktif)
APOTEK KF KEMANGGISAN
APOTEK PALU- (Non Aktif)
AQUA GOLDEN MISSISSIPI PT-AQUA KONSINYASI
AQUA GOLDEN MISSISSIPI PT-ENGGROS PO
ASKES-ASKES MALANG
ASKES-ASKES RAWAT INAP
ASKES-ASKES RAWAT JALAN
ASKES-DR KELUARGA
ASKES-DR KELUARGA KOM
ASKES-DR KELUARGA SOS
ASKES-DR. PURWANINGSIH
ASKES-KOMERSIAL BATAM
ASKES-KRONIS
ASKES-NON DPHO
ASKES-RJTP
ASKES-SOSIAL INAP
ASKES-SUKARELA
ASKES-SUKARELA RW. INAP
ASKES-SUKARELA RW. JALAN
ASKES-WAJIB RW. INAP
ASKES-WAJIB RW. JALAN
ASTRA GRAPHIA-
ASURANSI ADIRA DINAMIKA P-
ASURANSI AXA INDONESIA PT
ASURANSI BINTANG PT
ASURANSI CENTRAL ASIA PT-
ASURANSI JASA INDONESIA P-
ASURANSI JIWA CENTRAL ASI-
ASURANSI JIWA GENERALI IN-
ASURANSI JIWA INHEALTH IN-
ASURANSI JIWA INHEALTH INDONESIA PT-INHEALTH FEE FOR SERVICE
ASURANSI JIWA INHEALTH INDONESIA PT-INHEALTH INDEMNITY
ASURANSI JIWA INHEALTH INDONESIA PT-INHEALTH KAPITASI
ASURANSI JIWA INHEALTH INDONESIA PT-INHEALTH KLINIK
ASURANSI JIWA INHEALTH INDONESIA PT-INHEALTH RUJUK BALIK
ASURANSI JIWA JIWASRAYA P
ASURANSI JIWA SINAR MAS M-
ASURANSI JIWA TUGU MANDIR-
ASURANSI MITRA MAPARYA PT
ASURANSI SINAR MAS PT-
ASURANSI UMUM BUMIPUTERAM-
AVRIST ASSURANCE PT-AVRIST ASSURANCE WIL C
BADAN PEMERIKSA KEUANGAN-
BALAI PENGOBATAN WEST JAV-
BANK MANDIRI-DEPOK
BANK MANDIRI-MANADO
BANK MANDIRI-PALU
BANK MANDIRI-SEMARANG
BANK MANDIRI-TASIKMALAYA OTISTA
BANK MANDIRI-YOGYAKARTA
BNI 46 LIFE INSURANCE PT-
BNI 46 LIFE INSURANCE PT-BNI 46 LIFE INSURANCE MC,JAYA1
BON KARYAWAN KFA-
BON KARYAWAN KFA-BON KARYAWAN KFA MALANG
BON PENSIUNAN KF
BPJS KAPITASI BOGOR-
BPJS KAPITASI BOGOR-TEST
BPJS KAPITASI JAYA 1-
BPJS KAPITASI JAYA 2-Rawat Jalan Unit Bisnis Jaya 2
BPJS KAPITASI-
BPJS KAPITASI-BPJS KAPITASI BANDUNG
BPJS KESEHATAN BANDUNG-PASIEN RUJUK BALIK
BPJS KESEHATAN BOGOR-ALKES
BPJS KESEHATAN BOGOR-IGD
BPJS KESEHATAN BOGOR-OPTIK
BPJS KESEHATAN BOGOR-PASIEN KRONIS
BPJS KESEHATAN BOGOR-PASIEN RUJUK BALIK (Non Aktif)
BPJS KESEHATAN BOGOR-PROLANIS
BPJS KESEHATAN BOGOR-RAWAT INAP
BPJS KESEHATAN BOGOR-RAWAT JALAN
BPJS KESEHATAN CIREBON-PASIEN RUJUK BALIK (Non Aktif)
BPJS KESEHATAN JAYA 1
BPJS KESEHATAN JAYA 1-RAWAT INAP
BPJS KESEHATAN JAYA 1-RAWAT JALAN
BPJS KESEHATAN JAYA 2-
BPJS KESEHATAN JAYA 2-PASIEN KRONIS
BPJS KESEHATAN JAYA 2-PASIEN RUJUK BALIK
BPJS KESEHATAN JAYA 2-RAWAT JALAN
BPJS KESEHATAN JAYA 2-kelas 1
BPJS KESEHATAN JAYA 2-kelas 2
BPJS RUJUK BALIK-DEFAULT
BPJS Rawat Inap-INSTALASI FARMASI RSCM - SAS
BPJS Rawat Jalan-
BPKP PUSAT-
BUKIT ASAM PT-BUKIT ASAM - KANTOR TAMBANG
BUKIT ASAM PT-BUKIT ASAM - PENSIUNAN
BUKIT ASAM PT-BUKIT ASAM - TAMBANG
CONOCOPHILLIPS INDONESIA
DAMRI-
DEPOT LOGISTIK JAYA
DIKLUSEPORA (PDK)
DINAS NAKERTRANS SULTENG
DOKTER &amp; KARYAWAN RSAB
DOKTER - DOKTER-
DOKTER INHOUSE-
DOVER CHEMICAL PT-
DR KO KING TJOEN-
DR ROH PRABOWO-
DR SUPRAYITNO-
ENGGROS SWASTA-
GARUDA INDONESIA PT-JASA MEDICA
GARUDA INDONESIA PT-JPK-I MANADO
GARUDA INDONESIA PT-SENTRA MEDIKA
GARUDA INDONESIA PT-SENTRA MEDIKA -AEROWISATA
GARUDA INDONESIA PT-SENTRA MEDIKA JPK I
GARUDA INDONESIA PT-SENTRA MEDIKA JPK II
GARUDA INDONESIA PT-SENTRA MEDIKA JPK III
GELORA BUNG KARNO (100%)
GEO DIPA ENERGI PT
GEO DIPA ENERGI PT
GOODYEAR INDONESIA-
GRAMEDIA PT-CORPORATE ADVERTISING
GRAMEDIA PT-CORPORATE CIRCULATION
GRAMEDIA PT-CORPORATE COMMUNICATION
GRAMEDIA PT-CORPORATE CONTROLLER
GRAMEDIA PT-CORPORATE FACILITY MANAGEMEN
GRAMEDIA PT-CORPORATE HUMAN RESOURCES
GRAMEDIA PT-GROUP OF BOOKS PUBLISHING
GRAMEDIA PT-GROUP OF MAGAZINE
GRAMEDIA PT-GROUP OF PRINTING
GRAMEDIA PT-KOMPAS
GRAMEDIA PT-KONTAN
GRAMEDIA PT-MULTI MEDIA (MMSP)
GRAMEDIA PT-PERCETAKAN
GRAMEDIA PT-TRANSITO ADIMANJATI
GREAT EASTERN INSURANCE P
HANHWA LIFE
IOM
JASA RAHARJA PT-
JIEP PT
JPK DASAR RAWAT JALAN(DUK
KANWIL DIREKTORAT JENDERA
KBN PRIOK- (Non Aktif)
KEHUTANAN PHPA
KEHUTANAN PHPA POLIKLINIK
KF HOLDING AFILIASI (NON AKTIF)-PEMASARAN
KF HOLDING AFILIASI PROMOSI(NON AKTIF)
KF HOLDING AFILIASI(NON AKTIF)
KF PLANT JAKARTA
KF UNIT LOGISTIK SENTRAL
KFA PUSAT
KFTD AFILIASI-KFTD ACEH
KFTD AFILIASI-KFTD UNIT BISNIS PUSAT
KIMIA FARMA DIAGNOSTIK-
KLINIK BUKIT CIRENDEU
KLINIK MEDIKA BINA SEJAHT
KPB--
KPB-HN TU
KPB-NS SAWIT
KPB-NS TEH
KPB-NS TU
KPB-ST ANALISA PASAR
KPB-ST GULA
KPB-ST SAWIT
KPB-ST SPI
KPB-ST TEH
KPB-ST TU
KPP PENANAMAN MODAL ASING
KPP PRATAMA MATRAMAN-
KPPN JAKARTA-
KPPN PASAR REBO
KREDIT LAIN-LAIN (RELASI)-
LEMBAGA PENDIDIKAN PERKEB
MAHKAMAH AGUNG-
MAKO ARMABAR (Non Aktif)
MEGA ELTRA PT
MITRA KELUARGA PIRANTI SE-
Medevo-PLN KANTOR PUSAT TANGERANG
NAYAKA ERA HUSADA PT-JKP
NAYAKA ERA HUSADA PT-JPK PLUS
NAYAKA ERA HUSADA PT-JPK PLUS KELAS 1
NAYAKA ERA HUSADA PT-KELAS 2
NAYAKA ERA HUSADA PT-NAYAKA ERA HUSADA, BANDUNG
OLYMPIC GARMENT PT
OWLEXA INDONESIA-DEFAULT
PAM JAYA PT
PASPAMPRES
PELNI PT-
PERFETTI VAN MELLE INDONE-
PERPUSTAKAAN NASIONAL-
PERTAMEDIKA MEDICAL CENTR-
PERUM LPPNPI-
PERUSAHAAN SWASTA-
PETROSEA PT
PLN (PERSERO) JASA SERTIF
PLN (PERSERO) WILAYAH KALTIM, PT-DEFAULT
PLN AJ GAMBIR PENSIUNAN
PLN AJ GAMBIR-
PLN AJ JATINEGARA
PLN AJ KEBAYORAN
PLN AJ KEBAYORAN PENSIUNA
PLN AJ KRAMAT JATI
PLN AJ KRAMATJATI PENSIUN
PLN AJ TANGERANG
PLN AP BANDENGAN
PLN AP BINTARO
PLN AP BULUNGAN
PLN AP BULUNGAN PENSIUNAN
PLN AP CEMPAKA PUTIH
PLN AP CENGKARENG
PLN AP CIKOKOL
PLN AP CIKOKOL PENSIUNAN
PLN AP CIKUPA
PLN AP CILEDUK
PLN AP CILEDUK PENSIUNAN
PLN AP CINERE
PLN AP CIPUTAT
PLN AP CIRACAS
PLN AP CONDET
PLN AP GAMBIR (Non Aktif)
PLN AP GROGOL
PLN AP GUNUNG SAHARI
PLN AP JATINEGARA
PLN AP KALIDERES
PLN AP KALIMALANG
PLN AP KEBAYORAN
PLN AP KEBON JERUK
PLN AP KOTA
PLN AP KRAMAT JATI
PLN AP LENTENG AGUNG
PLN AP MAMPANG
PLN AP MARUNDA
PLN AP MENTENG
PLN AP PAMULANG
PLN AP PASAR MINGGU
PLN AP PONDOK GEDE
PLN AP PONDOK KOPI
PLN AP RAWAMANGUN
PLN AP SERPONG
PLN AP SUNTER PENSIUNAN
PLN AP TANGERANG-
PLN AP TANJUNG PRIOK
PLN APD SEMARANG-
PLN BANGKA BELITUNG-DEFAULT
PLN BENGKEL KLENDER PEGAW
PLN BENGKEL KLENDER PENSI
PLN CAB I WIL. V
PLN CAB II A.YANI
PLN CAB III KAPUAS
PLN DIST CABANG BOGOR
PLN DIST JABAR &amp; BANTEN-
PLN DIST JATENG &amp; DIY-
PLN DIST JATENG &amp; DIY-
PLN DIST JATIM
PLN DIST JATIM-PLN DIST JATIM MALANG
PLN DIST JAWA BARAT (KARA-
PLN DIST JAYA &amp; TANGERANG-Unit Bisnis Jaya 2
PLN DIST LAMPUNG-
PLN JASA SERTIFIKASI-
PLN JASDIK PENSIUNAN
PLN JASDIK U JAKARTA
PLN JASDIK UDIKLAT-
PLN JASDIK WIJAYA
PLN JTK SATUAN BKU
PLN JTK SATUAN JTK
PLN JTK SATUAN PNS
PLN K.DISTRIBUSI PENSIUNA-
PLN KANTOR DISTRIBUSI-
PLN KANTOR PUSAT-
PLN KANTOR PUSAT-PLN KANTOR PUSAT SURABAYA
PLN KANTOR PUSAT-PLN KANTOR PUSAT, JAYA I
PLN KANTOR PUSAT-PLN KANTOR PUSAT, PEKALONGAN
PLN KANTOR PUSAT-PLN KANTOR PUSAT-BEKASI
PLN KIT TJB-DEFAULT
PLN LITBANG KETENAGA LIST
PLN LITBANG SATUAN BKIT
PLN LITBANG SATUAN BMPS
PLN LITBANG SATUAN BSAK
PLN LITBANG SATUAN BTND
PLN LITBANG SATUAN GM LIT
PLN P2B AREA PENGATUR BEB-
PLN P3B JAWA BALI-
PLN P3B UBS PENSIUNAN
PLN P3B UBS-
PLN P3B UPBC-
PLN P3B UPT-
PLN P3B-PLN P3B MALANG
PLN PEMBANGKIT TANJUNG JA
PLN PJB I-
PLN PJB II MUARA KARANG
PLN PJB PENSIUNAN-PLN PJB PENSIUNAN MALANG
PLN PROKITRING
PLN PROYEK JARINGAN (JATE-
PLN PROYEK JARINGAN TIMUR-
PLN PT
PLN PUSAT BAGIAN SPI
PLN PUSAT PEGAWAI-
PLN PUSAT PEL ENGINEERING-
PLN PUSAT PENSIUNAN
PLN PUSAT POLIKLINIK
PLN PUSDIKLAT-
PLN PUSHARLIS-
PLN PUSLITBANG-
PLN SEKTOR P3B BOGOR
PLN SEKTOR PEMBANGKIT-
PLN SEKTOR PENSIUNAN BOGO-
PLN SEKTOR RANGKAS BOGOR
PLN SEKTOR UJT BOGOR
PLN SEKTOR UPT BOGOR
PLN TRANSMISI JAWA BAG BA-
PLN TRANSMISI JAWA BAG TE-
PLN TRANSMISI JAWA BAG TI
PLN TRANSMISI SUMBAR-
PLN UDIKLAT PENSIUNAN
PLN UDIKLAT SISWA
PLN UDIKLAT-
PLN UIP SULAWESI MALUKU P
PLN UJT KELISTRIKAN
PLN UJT PULO GADUNG
PLN UNIT INSTALASI PEMBAN-
PLN UNIT KANTOR DISTRIBUS
PLN UNIT PENGATUR DISTRIB
PLN UPT BANDA ACEH-
PLN WILAYAH KALSEL &amp; KALT-
PLN WILAYAH NTB
PLN WILAYAH PAPUA-
PLN WILAYAH SULSELBAR-DEFAULT
PLN WILAYAH SULUTTENGGO-DEFAULT
PLN WILAYAH SUMBAR PEGAWA
PLN WILAYAH SUMBAR-DEFAULT
PLN WILAYAH SUMUT-DEFAULT
PLN WILAYAH V PONTIANAK
POLIKLINIK BEA &amp; CUKAI (T
POLIKLINIK CENDANA-
POLIKLINIK INSTANSI-
POLIKLINIK SWASTA-
POLIKLINIK TAMAN SAFARI-
POS INDONESIA PT-CABANG BAGINDO AZIZ KHAN (Non Aktif)
POS INDONESIA PT-KANWIL
POS INDONESIA PT-PENSIUNAN
POS INDONESIA PT-WILAYAH KHATIB SULAIMAN
PPATK-
PT. KIMIA FARMA DIAGNOSTIKA-DEFAULT
PT. PERTAMINA HULU ENERGI (PHE)-DEFAULT
PUSRI PT
RESEP PEGAWAI SENDIRI-DEFAULT
RS DR H MARZOEKI MAHDI-
RS GATOT SUBROTO-
RS HARAPAN KITA
RS HERMINA TANGERANG-
RS HERMINA-
RS PEMERINTAH-
RS PERTAMINA JAYA-
RS SWASTA-
RS TEBET-
RSCM-BPJS ALAT DENGAR RSCM
RSCM-BPJS KRONIS RSCM
RSCM-BPJS R. INAP RSCM
RSCM-BPJS R. JALAN RSCM
RSCM-DIREKSI RSCM
RSCM-INSTALASI FARMASI RSCM - CITO
RSCM-INSTALASI FARMASI RSCM - OBAT
RSCM-INSTALASI FARMASI RSCM - RESEP
RSCM-JAMKESDA RAWAT JALAN RSCM
RSCM-KEMOTERAPI RSCM
RSCM-UNIT JAMINAN RSCM ( UPPJ )
RSCM-UNIT KARYAWAN RSCM JAKARTA
RST CIREMAI-
RSUD TARAKAN
SAHID SAHIRMAN MEMORIAL HOSPITAL-ASS RAWAT JALAN
SAHID SAHIRMAN MEMORIAL HOSPITAL-ASS RI KELAS A
SAHID SAHIRMAN MEMORIAL HOSPITAL-ASS RI KELAS B
SAHID SAHIRMAN MEMORIAL HOSPITAL-ASS RI SUITE
SAHID SAHIRMAN MEMORIAL HOSPITAL-ASS RI VIP
SAHID SAHIRMAN MEMORIAL HOSPITAL-BHP
SAHID SAHIRMAN MEMORIAL HOSPITAL-BPJS KHEMO
SAHID SAHIRMAN MEMORIAL HOSPITAL-BPJS KRONIS
SAHID SAHIRMAN MEMORIAL HOSPITAL-BPJS RW INAP
SAHID SAHIRMAN MEMORIAL HOSPITAL-BPJS RW JALAN
SAHID SAHIRMAN MEMORIAL HOSPITAL-ICCU
SAHID SAHIRMAN MEMORIAL HOSPITAL-ICU
SAHID SAHIRMAN MEMORIAL HOSPITAL-IGD
SAHID SAHIRMAN MEMORIAL HOSPITAL-RI KELAS A
SAHID SAHIRMAN MEMORIAL HOSPITAL-RI KELAS B
SAHID SAHIRMAN MEMORIAL HOSPITAL-RI KELAS SUITE
SAHID SAHIRMAN MEMORIAL HOSPITAL-RI KELAS VIP
SAHID SAHIRMAN MEMORIAL HOSPITAL-SAHID GROUP DIREKSI-KOMISARIS
SETIAJAYA MOBILINDO PT-
SHARP YASONTA PT
SHELF DRILLING PT
SIAPDOK-
STAFF WAPRES-
STAR ENERGY PT
SUMBER CIPTA MULTINIAGA P-
SWAKELOLA KESEHATAN KFA-
SYNGENTA PT-
TAMAN MINI INDONESIA INDA-
TELKOM PT JAKARTA
TELKOM PT-
TELKOMEDIKA PT-
TEUKU UMAR POLIKLINIK-POLIKLINIK II
TEUKU UMAR POLIKLINIK-POLIKLINIK III
TEUKU UMAR POLIKLINIK-POLIKLINIK IV
TIRTA INVESTAMA PT-
TIRTA INVESTAMA PT-BOGOR
TIRTA INVESTAMA PT-CIANJUR
TIRTA INVESTAMA PT-CIBINONG
TIRTA INVESTAMA PT-CILEGON
TIRTA INVESTAMA PT-CIPUTAT
TIRTA INVESTAMA PT-CITEUREUP
TIRTA INVESTAMA PT-CYBER
TIRTA INVESTAMA PT-DEPO
TIRTA INVESTAMA PT-DEPO (DR LUAR)
TIRTA INVESTAMA PT-DEPO (KLINIK)
TIRTA INVESTAMA PT-DEPO MANAGER
TIRTA INVESTAMA PT-DIREKTUR
TIRTA INVESTAMA PT-DISTRIBUSI
TIRTA INVESTAMA PT-ENGGRO (PO)
TIRTA INVESTAMA PT-ENGROS/SUBANG
TIRTA INVESTAMA PT-HEAD OFFICE
TIRTA INVESTAMA PT-HO DIREKTUR
TIRTA INVESTAMA PT-HO MANAGER
TIRTA INVESTAMA PT-KEBON C
TIRTA INVESTAMA PT-KEMBANGAN
TIRTA INVESTAMA PT-PABRIK
TIRTA INVESTAMA PT-PABRIK (DR LUAR)
TIRTA INVESTAMA PT-PABRIK (KLINIK)
TIRTA INVESTAMA PT-PLT HO
TIRTA INVESTAMA PT-POLANHARJO
TIRTA INVESTAMA PT-POLI
TIRTA INVESTAMA PT-POLI PANDAAN
TIRTA INVESTAMA PT-PULO KAMBING
TIRTA INVESTAMA PT-R/ BANDUNG (Non Aktif)
TIRTA INVESTAMA PT-R/SUBANG (Non Aktif)
TIRTA INVESTAMA PT-RAWA DOMBA
TIRTA INVESTAMA PT-SALES &amp; DISTRIBUSI
TIRTA INVESTAMA PT-SUPPLY CHAIN
TIRTA INVESTAMA PT-SURABAYA
TIRTA INVESTAMA PT-SURAKARTA
TIRTA INVESTAMA PT-WONOSOBO
TIRTA INVESTAMA PT-YOGYAKARTA
TUNAI
TUNAI
TUNAI-
TUNAI-KHUSUS
TUNAI-SINAR MAS
TUNAI-TAMBAH BAYAR
TUNGGAL IDAMAN ABADI PT-
WISMA NEGARA-
YAMAHA INDONESIA MOTOR MF-
YAYASAN DARUL HIKAM
YAYASAN GINJAL DIATRANS I
YKKBI- (Non Aktif)
YKKBI-YKKBI, DEPOK
YKP BANK BJB-YKP BANK BJB-AVP VP
YKP BANK BJB-YKP BANK BJB-Off SM
YKP BANK BJB-YKP BANK BJB-STAFF
YKP BANK BJB-YKP BANK BJB-SVP SEVP
YKP OJK-ADMEDIKA PAYOR PT- 






Nama Pasien*

Nama pasien harus diisi


Nomor Telepon*

Nomor telepon harus diisi


Alamat Pasien*

Alamat pasien harus diisi




Tanggal Lahir



NIK





Dokter*






Dokter harus diisi


PPK Asal*






PPK asal harus diisi


Poli*






Poli harus diisi


Alamat Dokter Praktik*

Alamat dokter harus diisi




    .tosca {
        color: #9e9e9e;
        text-transform: capitalize;
    }


      
        
          Nomor Kartu
          
            Cari PesertaCari Peserta
        
      


    
        
            Nama Peserta*
            
        

        
        
        
        
                    
                        
                            
    No. resep*

    




  Peentar.executeLater(function(){
  Peentar.Materialize.refreshForm($(&quot; , &quot;'&quot; , &quot;form&quot; , &quot;'&quot; , &quot;));
  var poly_url = $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).data(&quot; , &quot;'&quot; , &quot;url&quot; , &quot;'&quot; , &quot;);
  $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).select2({
    minimumInputLength: 3,
    ajax: {
      dataType: &quot; , &quot;'&quot; , &quot;json&quot; , &quot;'&quot; , &quot;,
      delay: 1000,
      url: poly_url,
      data: function (params) {
        var query = {
          q: params.term
        };
        return query;
      },
      processResults: function (data) {
        if (data.error){
          Materialize.toast(&quot;Koneksi Bermasalah&quot;, 3000);
          return false;
        }
        return {
          results: data.poly
        };
      },
    },
  });

  $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).on(&quot; , &quot;'&quot; , &quot;select2:select&quot; , &quot;'&quot; , &quot;, function (e) {

          $(&quot; , &quot;'&quot; , &quot;#poly&quot; , &quot;'&quot; , &quot;).val(e.params.data.text);

  });

})


                        
                    
                        
                            
    Npp*

    




  Peentar.executeLater(function(){
  Peentar.Materialize.refreshForm($(&quot; , &quot;'&quot; , &quot;form&quot; , &quot;'&quot; , &quot;));
  var poly_url = $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).data(&quot; , &quot;'&quot; , &quot;url&quot; , &quot;'&quot; , &quot;);
  $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).select2({
    minimumInputLength: 3,
    ajax: {
      dataType: &quot; , &quot;'&quot; , &quot;json&quot; , &quot;'&quot; , &quot;,
      delay: 1000,
      url: poly_url,
      data: function (params) {
        var query = {
          q: params.term
        };
        return query;
      },
      processResults: function (data) {
        if (data.error){
          Materialize.toast(&quot;Koneksi Bermasalah&quot;, 3000);
          return false;
        }
        return {
          results: data.poly
        };
      },
    },
  });

  $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).on(&quot; , &quot;'&quot; , &quot;select2:select&quot; , &quot;'&quot; , &quot;, function (e) {

          $(&quot; , &quot;'&quot; , &quot;#poly&quot; , &quot;'&quot; , &quot;).val(e.params.data.text);

  });

})


                        
                    
                        
                            
    Nama_pasien*

    




  Peentar.executeLater(function(){
  Peentar.Materialize.refreshForm($(&quot; , &quot;'&quot; , &quot;form&quot; , &quot;'&quot; , &quot;));
  var poly_url = $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).data(&quot; , &quot;'&quot; , &quot;url&quot; , &quot;'&quot; , &quot;);
  $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).select2({
    minimumInputLength: 3,
    ajax: {
      dataType: &quot; , &quot;'&quot; , &quot;json&quot; , &quot;'&quot; , &quot;,
      delay: 1000,
      url: poly_url,
      data: function (params) {
        var query = {
          q: params.term
        };
        return query;
      },
      processResults: function (data) {
        if (data.error){
          Materialize.toast(&quot;Koneksi Bermasalah&quot;, 3000);
          return false;
        }
        return {
          results: data.poly
        };
      },
    },
  });

  $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).on(&quot; , &quot;'&quot; , &quot;select2:select&quot; , &quot;'&quot; , &quot;, function (e) {

          $(&quot; , &quot;'&quot; , &quot;#poly&quot; , &quot;'&quot; , &quot;).val(e.params.data.text);

  });

})


                        
                    
                        
                            
    Nama obat*

    




  Peentar.executeLater(function(){
  Peentar.Materialize.refreshForm($(&quot; , &quot;'&quot; , &quot;form&quot; , &quot;'&quot; , &quot;));
  var poly_url = $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).data(&quot; , &quot;'&quot; , &quot;url&quot; , &quot;'&quot; , &quot;);
  $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).select2({
    minimumInputLength: 3,
    ajax: {
      dataType: &quot; , &quot;'&quot; , &quot;json&quot; , &quot;'&quot; , &quot;,
      delay: 1000,
      url: poly_url,
      data: function (params) {
        var query = {
          q: params.term
        };
        return query;
      },
      processResults: function (data) {
        if (data.error){
          Materialize.toast(&quot;Koneksi Bermasalah&quot;, 3000);
          return false;
        }
        return {
          results: data.poly
        };
      },
    },
  });

  $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).on(&quot; , &quot;'&quot; , &quot;select2:select&quot; , &quot;'&quot; , &quot;, function (e) {

          $(&quot; , &quot;'&quot; , &quot;#poly&quot; , &quot;'&quot; , &quot;).val(e.params.data.text);

  });

})


                        
                    
                        
                            

TANGGAL RESEP




                        
       
 








  $(document).ready(function() {
      Peentar.datePicker(&quot;.datepicker&quot;);
  });







Jenis Resep



Resep Obat



Resep Optik










Obat Non-Racik

Obat Racik





Nama Obat







Item Penjamin






Jumlah



Harga Total (Rp)




Stok



Satuan



Harga Satuan (Rp)



Jumlah Resep



Jumlah Ambil



Harga (Rp)



Signa 1



Signa 2



JHO



Catatan




Cost Sharing




















Simpan









Racikan 1
KAPSUL
PUYER
SALEP
LARUTAN LUAR
LARUTAN DALAM
SUPPOSITORIA
BEDAK


Jumlah Racikan Resep




Jumlah Ambil Resep




Signa 1



Signa 2



JHO



Embalase (Rp)




Catatan




+ Obat









Nama Obat





delete



Item Penjamin





Jumlah




Harga Total (Rp)





Stok



Satuan




Harga Satuan (Rp)




Kekuatan Obat



Dosis Resep



Jumlah Resep




Jumlah Ambil




Harga (Rp)




Cost Sharing




SIMPAN



  function validateDecimal(e) {
    var t = e.value;
    e.value = (t.indexOf(&quot;.&quot;) >= 0) ? (t.substr(0, t.indexOf(&quot;.&quot;)) + t.substr(t.indexOf(&quot;.&quot;), 3)) : t;
  }








Nama Item






Stok



Kuantitas



Satuan



Harga (Rp)



Harga Total (Rp)

















Simpan








Daftar Produk


Preview Resep




  
    


    
        
        
        Belum memilih obat
    

  


  Total Harga Resep:
  Rp0




Batal


Lanjutkan



&quot;) or . = concat(&quot;



Alumni ITB



Ya



Tidak








Member






 




No Telepon



Nama Lengkap



Batal
Simpan







Pilih Metode Bayar


Tunai



Kredit Resep
-pilih jaminan-
 NESTLE INDONESIA PT -NESTLE INDONESIA PT MALANG
ABDA-
ADMEDIKA PAYOR PT 2-   
ADMEDIKA PAYOR PT-
ADMEDIKA PAYOR PT- 
ADMEDIKA PAYOR PT-AIA
ADMEDIKA PAYOR PT-AIA INDIVIDU
ADMEDIKA PAYOR PT-ALLIANZ
ADMEDIKA PAYOR PT-ASTRA BUANA
ADMEDIKA PAYOR PT-ASURANSI AXA INDONESIA
ADMEDIKA PAYOR PT-AVIVA
ADMEDIKA PAYOR PT-AXA MANDIRI
ADMEDIKA PAYOR PT-BANK MANDIRI INHEALTH
ADMEDIKA PAYOR PT-BNI LIFE INSURANCE
ADMEDIKA PAYOR PT-BUKOPIN
ADMEDIKA PAYOR PT-BULOG
ADMEDIKA PAYOR PT-COMMONWEALTH LIFE
ADMEDIKA PAYOR PT-EQUITY
ADMEDIKA PAYOR PT-FWD
ADMEDIKA PAYOR PT-GENERALI
ADMEDIKA PAYOR PT-GREAT EASTERN INSURANCE
ADMEDIKA PAYOR PT-HANHWA LIFE
ADMEDIKA PAYOR PT-ICON +
ADMEDIKA PAYOR PT-INDEMNITY
ADMEDIKA PAYOR PT-INDOSURYA LIFE
ADMEDIKA PAYOR PT-INHEALTH
ADMEDIKA PAYOR PT-JIWA RECAPITAL INSURANCE
ADMEDIKA PAYOR PT-JIWA SINARMAS
ADMEDIKA PAYOR PT-KARYAWAN &amp; KELUARGA
ADMEDIKA PAYOR PT-KOPELINDO BULOG
ADMEDIKA PAYOR PT-LION SUPERINDO
ADMEDIKA PAYOR PT-MAYBANK
ADMEDIKA PAYOR PT-MEGA HEALTH
ADMEDIKA PAYOR PT-MEGA INSURANCE
ADMEDIKA PAYOR PT-MNC LIFE
ADMEDIKA PAYOR PT-NUSANTARA REGAS
ADMEDIKA PAYOR PT-OJK
ADMEDIKA PAYOR PT-PT JOB PERTAMINA
ADMEDIKA PAYOR PT-RELIANCE
ADMEDIKA PAYOR PT-SINAR MAS
ADMEDIKA PAYOR PT-SOMPO
ADMEDIKA PAYOR PT-SUN LIFE FINANCIAL
ADMEDIKA PAYOR PT-TELKOMEDIKA
ADMEDIKA PAYOR PT-TOKIO MARINE LIFE INSURANCE
ADMEDIKA PAYOR PT-TRI TUNGGAL MANDIRI
ADMEDIKA PAYOR PT-TUGU PRATAMA INDO
ADMEDIKA PAYOR PT-WANAARTHA LIFE
ADMEDIKA PAYOR PT-WIJAYA KARYA
ADMEDIKA PAYOR PT-WINTERTHUR
ANEKA TAMBANG PT-CIKOTOK
ANEKA TAMBANG PT-GEBE
ANEKA TAMBANG PT-PEGAWAI
ANEKA TAMBANG PT-PENSIUNAN
ANEKA TAMBANG PT-POMALAA
ANEKA TAMBANG PT-PONGKOR
ANEKA TAMBANG PT-YAKESPEN
ANGKASA PURA I POLIKLINIK-DEFAULT
ANGKASA PURA I PT-
ANGKASA PURA II PT-
ANGKASA PURA II PT-AIRNAV
ANGKASA PURA II PT-CABANG
ANGKASA PURA II PT-DIREKSI
ANGKASA PURA II PT-GADAR MEDIK
ANGKASA PURA II PT-HALIM
ANGKASA PURA II PT-KELUARGA
ANGKASA PURA II PT-LUAR KOTA
ANGKASA PURA II PT-PENSIUNAN
ANGKASA PURA II PT-POLIKLINIK
APOTEK - APOTEK- (Non Aktif)
APOTEK KF KEMANGGISAN
APOTEK PALU- (Non Aktif)
AQUA GOLDEN MISSISSIPI PT-AQUA KONSINYASI
AQUA GOLDEN MISSISSIPI PT-ENGGROS PO
ASKES-ASKES MALANG
ASKES-ASKES RAWAT INAP
ASKES-ASKES RAWAT JALAN
ASKES-DR KELUARGA
ASKES-DR KELUARGA KOM
ASKES-DR KELUARGA SOS
ASKES-DR. PURWANINGSIH
ASKES-KOMERSIAL BATAM
ASKES-KRONIS
ASKES-NON DPHO
ASKES-RJTP
ASKES-SOSIAL INAP
ASKES-SUKARELA
ASKES-SUKARELA RW. INAP
ASKES-SUKARELA RW. JALAN
ASKES-WAJIB RW. INAP
ASKES-WAJIB RW. JALAN
ASTRA GRAPHIA-
ASURANSI ADIRA DINAMIKA P-
ASURANSI AXA INDONESIA PT
ASURANSI BINTANG PT
ASURANSI CENTRAL ASIA PT-
ASURANSI JASA INDONESIA P-
ASURANSI JIWA CENTRAL ASI-
ASURANSI JIWA GENERALI IN-
ASURANSI JIWA INHEALTH IN-
ASURANSI JIWA INHEALTH INDONESIA PT-INHEALTH FEE FOR SERVICE
ASURANSI JIWA INHEALTH INDONESIA PT-INHEALTH INDEMNITY
ASURANSI JIWA INHEALTH INDONESIA PT-INHEALTH KAPITASI
ASURANSI JIWA INHEALTH INDONESIA PT-INHEALTH KLINIK
ASURANSI JIWA INHEALTH INDONESIA PT-INHEALTH RUJUK BALIK
ASURANSI JIWA JIWASRAYA P
ASURANSI JIWA SINAR MAS M-
ASURANSI JIWA TUGU MANDIR-
ASURANSI MITRA MAPARYA PT
ASURANSI SINAR MAS PT-
ASURANSI UMUM BUMIPUTERAM-
AVRIST ASSURANCE PT-AVRIST ASSURANCE WIL C
BADAN PEMERIKSA KEUANGAN-
BALAI PENGOBATAN WEST JAV-
BANK MANDIRI-DEPOK
BANK MANDIRI-MANADO
BANK MANDIRI-PALU
BANK MANDIRI-SEMARANG
BANK MANDIRI-TASIKMALAYA OTISTA
BANK MANDIRI-YOGYAKARTA
BNI 46 LIFE INSURANCE PT-
BNI 46 LIFE INSURANCE PT-BNI 46 LIFE INSURANCE MC,JAYA1
BON KARYAWAN KFA-
BON KARYAWAN KFA-BON KARYAWAN KFA MALANG
BON PENSIUNAN KF
BPJS KAPITASI BOGOR-
BPJS KAPITASI BOGOR-TEST
BPJS KAPITASI JAYA 1-
BPJS KAPITASI JAYA 2-Rawat Jalan Unit Bisnis Jaya 2
BPJS KAPITASI-
BPJS KAPITASI-BPJS KAPITASI BANDUNG
BPJS KESEHATAN BANDUNG-PASIEN RUJUK BALIK
BPJS KESEHATAN BOGOR-ALKES
BPJS KESEHATAN BOGOR-IGD
BPJS KESEHATAN BOGOR-OPTIK
BPJS KESEHATAN BOGOR-PASIEN KRONIS
BPJS KESEHATAN BOGOR-PASIEN RUJUK BALIK (Non Aktif)
BPJS KESEHATAN BOGOR-PROLANIS
BPJS KESEHATAN BOGOR-RAWAT INAP
BPJS KESEHATAN BOGOR-RAWAT JALAN
BPJS KESEHATAN CIREBON-PASIEN RUJUK BALIK (Non Aktif)
BPJS KESEHATAN JAYA 1
BPJS KESEHATAN JAYA 1-RAWAT INAP
BPJS KESEHATAN JAYA 1-RAWAT JALAN
BPJS KESEHATAN JAYA 2-
BPJS KESEHATAN JAYA 2-PASIEN KRONIS
BPJS KESEHATAN JAYA 2-PASIEN RUJUK BALIK
BPJS KESEHATAN JAYA 2-RAWAT JALAN
BPJS KESEHATAN JAYA 2-kelas 1
BPJS KESEHATAN JAYA 2-kelas 2
BPJS RUJUK BALIK-DEFAULT
BPJS Rawat Inap-INSTALASI FARMASI RSCM - SAS
BPJS Rawat Jalan-
BPKP PUSAT-
BUKIT ASAM PT-BUKIT ASAM - KANTOR TAMBANG
BUKIT ASAM PT-BUKIT ASAM - PENSIUNAN
BUKIT ASAM PT-BUKIT ASAM - TAMBANG
CONOCOPHILLIPS INDONESIA
DAMRI-
DEPOT LOGISTIK JAYA
DIKLUSEPORA (PDK)
DINAS NAKERTRANS SULTENG
DOKTER &amp; KARYAWAN RSAB
DOKTER - DOKTER-
DOKTER INHOUSE-
DOVER CHEMICAL PT-
DR KO KING TJOEN-
DR ROH PRABOWO-
DR SUPRAYITNO-
ENGGROS SWASTA-
GARUDA INDONESIA PT-JASA MEDICA
GARUDA INDONESIA PT-JPK-I MANADO
GARUDA INDONESIA PT-SENTRA MEDIKA
GARUDA INDONESIA PT-SENTRA MEDIKA -AEROWISATA
GARUDA INDONESIA PT-SENTRA MEDIKA JPK I
GARUDA INDONESIA PT-SENTRA MEDIKA JPK II
GARUDA INDONESIA PT-SENTRA MEDIKA JPK III
GELORA BUNG KARNO (100%)
GEO DIPA ENERGI PT
GEO DIPA ENERGI PT
GOODYEAR INDONESIA-
GRAMEDIA PT-CORPORATE ADVERTISING
GRAMEDIA PT-CORPORATE CIRCULATION
GRAMEDIA PT-CORPORATE COMMUNICATION
GRAMEDIA PT-CORPORATE CONTROLLER
GRAMEDIA PT-CORPORATE FACILITY MANAGEMEN
GRAMEDIA PT-CORPORATE HUMAN RESOURCES
GRAMEDIA PT-GROUP OF BOOKS PUBLISHING
GRAMEDIA PT-GROUP OF MAGAZINE
GRAMEDIA PT-GROUP OF PRINTING
GRAMEDIA PT-KOMPAS
GRAMEDIA PT-KONTAN
GRAMEDIA PT-MULTI MEDIA (MMSP)
GRAMEDIA PT-PERCETAKAN
GRAMEDIA PT-TRANSITO ADIMANJATI
GREAT EASTERN INSURANCE P
HANHWA LIFE
IOM
JASA RAHARJA PT-
JIEP PT
JPK DASAR RAWAT JALAN(DUK
KANWIL DIREKTORAT JENDERA
KBN PRIOK- (Non Aktif)
KEHUTANAN PHPA
KEHUTANAN PHPA POLIKLINIK
KF HOLDING AFILIASI (NON AKTIF)-PEMASARAN
KF HOLDING AFILIASI PROMOSI(NON AKTIF)
KF HOLDING AFILIASI(NON AKTIF)
KF PLANT JAKARTA
KF UNIT LOGISTIK SENTRAL
KFA PUSAT
KFTD AFILIASI-KFTD ACEH
KFTD AFILIASI-KFTD UNIT BISNIS PUSAT
KIMIA FARMA DIAGNOSTIK-
KLINIK BUKIT CIRENDEU
KLINIK MEDIKA BINA SEJAHT
KPB--
KPB-HN TU
KPB-NS SAWIT
KPB-NS TEH
KPB-NS TU
KPB-ST ANALISA PASAR
KPB-ST GULA
KPB-ST SAWIT
KPB-ST SPI
KPB-ST TEH
KPB-ST TU
KPP PENANAMAN MODAL ASING
KPP PRATAMA MATRAMAN-
KPPN JAKARTA-
KPPN PASAR REBO
KREDIT LAIN-LAIN (RELASI)-
LEMBAGA PENDIDIKAN PERKEB
MAHKAMAH AGUNG-
MAKO ARMABAR (Non Aktif)
MEGA ELTRA PT
MITRA KELUARGA PIRANTI SE-
Medevo-PLN KANTOR PUSAT TANGERANG
NAYAKA ERA HUSADA PT-JKP
NAYAKA ERA HUSADA PT-JPK PLUS
NAYAKA ERA HUSADA PT-JPK PLUS KELAS 1
NAYAKA ERA HUSADA PT-KELAS 2
NAYAKA ERA HUSADA PT-NAYAKA ERA HUSADA, BANDUNG
OLYMPIC GARMENT PT
OWLEXA INDONESIA-DEFAULT
PAM JAYA PT
PASPAMPRES
PELNI PT-
PERFETTI VAN MELLE INDONE-
PERPUSTAKAAN NASIONAL-
PERTAMEDIKA MEDICAL CENTR-
PERUM LPPNPI-
PERUSAHAAN SWASTA-
PETROSEA PT
PLN (PERSERO) JASA SERTIF
PLN (PERSERO) WILAYAH KALTIM, PT-DEFAULT
PLN AJ GAMBIR PENSIUNAN
PLN AJ GAMBIR-
PLN AJ JATINEGARA
PLN AJ KEBAYORAN
PLN AJ KEBAYORAN PENSIUNA
PLN AJ KRAMAT JATI
PLN AJ KRAMATJATI PENSIUN
PLN AJ TANGERANG
PLN AP BANDENGAN
PLN AP BINTARO
PLN AP BULUNGAN
PLN AP BULUNGAN PENSIUNAN
PLN AP CEMPAKA PUTIH
PLN AP CENGKARENG
PLN AP CIKOKOL
PLN AP CIKOKOL PENSIUNAN
PLN AP CIKUPA
PLN AP CILEDUK
PLN AP CILEDUK PENSIUNAN
PLN AP CINERE
PLN AP CIPUTAT
PLN AP CIRACAS
PLN AP CONDET
PLN AP GAMBIR (Non Aktif)
PLN AP GROGOL
PLN AP GUNUNG SAHARI
PLN AP JATINEGARA
PLN AP KALIDERES
PLN AP KALIMALANG
PLN AP KEBAYORAN
PLN AP KEBON JERUK
PLN AP KOTA
PLN AP KRAMAT JATI
PLN AP LENTENG AGUNG
PLN AP MAMPANG
PLN AP MARUNDA
PLN AP MENTENG
PLN AP PAMULANG
PLN AP PASAR MINGGU
PLN AP PONDOK GEDE
PLN AP PONDOK KOPI
PLN AP RAWAMANGUN
PLN AP SERPONG
PLN AP SUNTER PENSIUNAN
PLN AP TANGERANG-
PLN AP TANJUNG PRIOK
PLN APD SEMARANG-
PLN BANGKA BELITUNG-DEFAULT
PLN BENGKEL KLENDER PEGAW
PLN BENGKEL KLENDER PENSI
PLN CAB I WIL. V
PLN CAB II A.YANI
PLN CAB III KAPUAS
PLN DIST CABANG BOGOR
PLN DIST JABAR &amp; BANTEN-
PLN DIST JATENG &amp; DIY-
PLN DIST JATENG &amp; DIY-
PLN DIST JATIM
PLN DIST JATIM-PLN DIST JATIM MALANG
PLN DIST JAWA BARAT (KARA-
PLN DIST JAYA &amp; TANGERANG-Unit Bisnis Jaya 2
PLN DIST LAMPUNG-
PLN JASA SERTIFIKASI-
PLN JASDIK PENSIUNAN
PLN JASDIK U JAKARTA
PLN JASDIK UDIKLAT-
PLN JASDIK WIJAYA
PLN JTK SATUAN BKU
PLN JTK SATUAN JTK
PLN JTK SATUAN PNS
PLN K.DISTRIBUSI PENSIUNA-
PLN KANTOR DISTRIBUSI-
PLN KANTOR PUSAT-
PLN KANTOR PUSAT-PLN KANTOR PUSAT SURABAYA
PLN KANTOR PUSAT-PLN KANTOR PUSAT, JAYA I
PLN KANTOR PUSAT-PLN KANTOR PUSAT, PEKALONGAN
PLN KANTOR PUSAT-PLN KANTOR PUSAT-BEKASI
PLN KIT TJB-DEFAULT
PLN LITBANG KETENAGA LIST
PLN LITBANG SATUAN BKIT
PLN LITBANG SATUAN BMPS
PLN LITBANG SATUAN BSAK
PLN LITBANG SATUAN BTND
PLN LITBANG SATUAN GM LIT
PLN P2B AREA PENGATUR BEB-
PLN P3B JAWA BALI-
PLN P3B UBS PENSIUNAN
PLN P3B UBS-
PLN P3B UPBC-
PLN P3B UPT-
PLN P3B-PLN P3B MALANG
PLN PEMBANGKIT TANJUNG JA
PLN PJB I-
PLN PJB II MUARA KARANG
PLN PJB PENSIUNAN-PLN PJB PENSIUNAN MALANG
PLN PROKITRING
PLN PROYEK JARINGAN (JATE-
PLN PROYEK JARINGAN TIMUR-
PLN PT
PLN PUSAT BAGIAN SPI
PLN PUSAT PEGAWAI-
PLN PUSAT PEL ENGINEERING-
PLN PUSAT PENSIUNAN
PLN PUSAT POLIKLINIK
PLN PUSDIKLAT-
PLN PUSHARLIS-
PLN PUSLITBANG-
PLN SEKTOR P3B BOGOR
PLN SEKTOR PEMBANGKIT-
PLN SEKTOR PENSIUNAN BOGO-
PLN SEKTOR RANGKAS BOGOR
PLN SEKTOR UJT BOGOR
PLN SEKTOR UPT BOGOR
PLN TRANSMISI JAWA BAG BA-
PLN TRANSMISI JAWA BAG TE-
PLN TRANSMISI JAWA BAG TI
PLN TRANSMISI SUMBAR-
PLN UDIKLAT PENSIUNAN
PLN UDIKLAT SISWA
PLN UDIKLAT-
PLN UIP SULAWESI MALUKU P
PLN UJT KELISTRIKAN
PLN UJT PULO GADUNG
PLN UNIT INSTALASI PEMBAN-
PLN UNIT KANTOR DISTRIBUS
PLN UNIT PENGATUR DISTRIB
PLN UPT BANDA ACEH-
PLN WILAYAH KALSEL &amp; KALT-
PLN WILAYAH NTB
PLN WILAYAH PAPUA-
PLN WILAYAH SULSELBAR-DEFAULT
PLN WILAYAH SULUTTENGGO-DEFAULT
PLN WILAYAH SUMBAR PEGAWA
PLN WILAYAH SUMBAR-DEFAULT
PLN WILAYAH SUMUT-DEFAULT
PLN WILAYAH V PONTIANAK
POLIKLINIK BEA &amp; CUKAI (T
POLIKLINIK CENDANA-
POLIKLINIK INSTANSI-
POLIKLINIK SWASTA-
POLIKLINIK TAMAN SAFARI-
POS INDONESIA PT-CABANG BAGINDO AZIZ KHAN (Non Aktif)
POS INDONESIA PT-KANWIL
POS INDONESIA PT-PENSIUNAN
POS INDONESIA PT-WILAYAH KHATIB SULAIMAN
PPATK-
PT. KIMIA FARMA DIAGNOSTIKA-DEFAULT
PT. PERTAMINA HULU ENERGI (PHE)-DEFAULT
PUSRI PT
RESEP PEGAWAI SENDIRI-DEFAULT
RS DR H MARZOEKI MAHDI-
RS GATOT SUBROTO-
RS HARAPAN KITA
RS HERMINA TANGERANG-
RS HERMINA-
RS PEMERINTAH-
RS PERTAMINA JAYA-
RS SWASTA-
RS TEBET-
RSCM-BPJS ALAT DENGAR RSCM
RSCM-BPJS KRONIS RSCM
RSCM-BPJS R. INAP RSCM
RSCM-BPJS R. JALAN RSCM
RSCM-DIREKSI RSCM
RSCM-INSTALASI FARMASI RSCM - CITO
RSCM-INSTALASI FARMASI RSCM - OBAT
RSCM-INSTALASI FARMASI RSCM - RESEP
RSCM-JAMKESDA RAWAT JALAN RSCM
RSCM-KEMOTERAPI RSCM
RSCM-UNIT JAMINAN RSCM ( UPPJ )
RSCM-UNIT KARYAWAN RSCM JAKARTA
RST CIREMAI-
RSUD TARAKAN
SAHID SAHIRMAN MEMORIAL HOSPITAL-ASS RAWAT JALAN
SAHID SAHIRMAN MEMORIAL HOSPITAL-ASS RI KELAS A
SAHID SAHIRMAN MEMORIAL HOSPITAL-ASS RI KELAS B
SAHID SAHIRMAN MEMORIAL HOSPITAL-ASS RI SUITE
SAHID SAHIRMAN MEMORIAL HOSPITAL-ASS RI VIP
SAHID SAHIRMAN MEMORIAL HOSPITAL-BHP
SAHID SAHIRMAN MEMORIAL HOSPITAL-BPJS KHEMO
SAHID SAHIRMAN MEMORIAL HOSPITAL-BPJS KRONIS
SAHID SAHIRMAN MEMORIAL HOSPITAL-BPJS RW INAP
SAHID SAHIRMAN MEMORIAL HOSPITAL-BPJS RW JALAN
SAHID SAHIRMAN MEMORIAL HOSPITAL-ICCU
SAHID SAHIRMAN MEMORIAL HOSPITAL-ICU
SAHID SAHIRMAN MEMORIAL HOSPITAL-IGD
SAHID SAHIRMAN MEMORIAL HOSPITAL-RI KELAS A
SAHID SAHIRMAN MEMORIAL HOSPITAL-RI KELAS B
SAHID SAHIRMAN MEMORIAL HOSPITAL-RI KELAS SUITE
SAHID SAHIRMAN MEMORIAL HOSPITAL-RI KELAS VIP
SAHID SAHIRMAN MEMORIAL HOSPITAL-SAHID GROUP DIREKSI-KOMISARIS
SETIAJAYA MOBILINDO PT-
SHARP YASONTA PT
SHELF DRILLING PT
SIAPDOK-
STAFF WAPRES-
STAR ENERGY PT
SUMBER CIPTA MULTINIAGA P-
SWAKELOLA KESEHATAN KFA-
SYNGENTA PT-
TAMAN MINI INDONESIA INDA-
TELKOM PT JAKARTA
TELKOM PT-
TELKOMEDIKA PT-
TEUKU UMAR POLIKLINIK-POLIKLINIK II
TEUKU UMAR POLIKLINIK-POLIKLINIK III
TEUKU UMAR POLIKLINIK-POLIKLINIK IV
TIRTA INVESTAMA PT-
TIRTA INVESTAMA PT-BOGOR
TIRTA INVESTAMA PT-CIANJUR
TIRTA INVESTAMA PT-CIBINONG
TIRTA INVESTAMA PT-CILEGON
TIRTA INVESTAMA PT-CIPUTAT
TIRTA INVESTAMA PT-CITEUREUP
TIRTA INVESTAMA PT-CYBER
TIRTA INVESTAMA PT-DEPO
TIRTA INVESTAMA PT-DEPO (DR LUAR)
TIRTA INVESTAMA PT-DEPO (KLINIK)
TIRTA INVESTAMA PT-DEPO MANAGER
TIRTA INVESTAMA PT-DIREKTUR
TIRTA INVESTAMA PT-DISTRIBUSI
TIRTA INVESTAMA PT-ENGGRO (PO)
TIRTA INVESTAMA PT-ENGROS/SUBANG
TIRTA INVESTAMA PT-HEAD OFFICE
TIRTA INVESTAMA PT-HO DIREKTUR
TIRTA INVESTAMA PT-HO MANAGER
TIRTA INVESTAMA PT-KEBON C
TIRTA INVESTAMA PT-KEMBANGAN
TIRTA INVESTAMA PT-PABRIK
TIRTA INVESTAMA PT-PABRIK (DR LUAR)
TIRTA INVESTAMA PT-PABRIK (KLINIK)
TIRTA INVESTAMA PT-PLT HO
TIRTA INVESTAMA PT-POLANHARJO
TIRTA INVESTAMA PT-POLI
TIRTA INVESTAMA PT-POLI PANDAAN
TIRTA INVESTAMA PT-PULO KAMBING
TIRTA INVESTAMA PT-R/ BANDUNG (Non Aktif)
TIRTA INVESTAMA PT-R/SUBANG (Non Aktif)
TIRTA INVESTAMA PT-RAWA DOMBA
TIRTA INVESTAMA PT-SALES &amp; DISTRIBUSI
TIRTA INVESTAMA PT-SUPPLY CHAIN
TIRTA INVESTAMA PT-SURABAYA
TIRTA INVESTAMA PT-SURAKARTA
TIRTA INVESTAMA PT-WONOSOBO
TIRTA INVESTAMA PT-YOGYAKARTA
TUNAI
TUNAI
TUNAI-
TUNAI-KHUSUS
TUNAI-SINAR MAS
TUNAI-TAMBAH BAYAR
TUNGGAL IDAMAN ABADI PT-
WISMA NEGARA-
YAMAHA INDONESIA MOTOR MF-
YAYASAN DARUL HIKAM
YAYASAN GINJAL DIATRANS I
YKKBI- (Non Aktif)
YKKBI-YKKBI, DEPOK
YKP BANK BJB-YKP BANK BJB-AVP VP
YKP BANK BJB-YKP BANK BJB-Off SM
YKP BANK BJB-YKP BANK BJB-STAFF
YKP BANK BJB-YKP BANK BJB-SVP SEVP
YKP OJK-ADMEDIKA PAYOR PT- 






Nama Pasien*

Nama pasien harus diisi


Nomor Telepon*

Nomor telepon harus diisi


Alamat Pasien*

Alamat pasien harus diisi




Tanggal Lahir



NIK





Dokter*






Dokter harus diisi


PPK Asal*






PPK asal harus diisi


Poli*






Poli harus diisi


Alamat Dokter Praktik*

Alamat dokter harus diisi




    .tosca {
        color: #9e9e9e;
        text-transform: capitalize;
    }


      
        
          Nomor Kartu
          
            Cari PesertaCari Peserta
        
      


    
        
            Nama Peserta*
            
        

        
        
        
        
                    
                        
                            
    No. resep*

    




  Peentar.executeLater(function(){
  Peentar.Materialize.refreshForm($(&quot; , &quot;'&quot; , &quot;form&quot; , &quot;'&quot; , &quot;));
  var poly_url = $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).data(&quot; , &quot;'&quot; , &quot;url&quot; , &quot;'&quot; , &quot;);
  $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).select2({
    minimumInputLength: 3,
    ajax: {
      dataType: &quot; , &quot;'&quot; , &quot;json&quot; , &quot;'&quot; , &quot;,
      delay: 1000,
      url: poly_url,
      data: function (params) {
        var query = {
          q: params.term
        };
        return query;
      },
      processResults: function (data) {
        if (data.error){
          Materialize.toast(&quot;Koneksi Bermasalah&quot;, 3000);
          return false;
        }
        return {
          results: data.poly
        };
      },
    },
  });

  $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).on(&quot; , &quot;'&quot; , &quot;select2:select&quot; , &quot;'&quot; , &quot;, function (e) {

          $(&quot; , &quot;'&quot; , &quot;#poly&quot; , &quot;'&quot; , &quot;).val(e.params.data.text);

  });

})


                        
                    
                        
                            
    Npp*

    




  Peentar.executeLater(function(){
  Peentar.Materialize.refreshForm($(&quot; , &quot;'&quot; , &quot;form&quot; , &quot;'&quot; , &quot;));
  var poly_url = $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).data(&quot; , &quot;'&quot; , &quot;url&quot; , &quot;'&quot; , &quot;);
  $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).select2({
    minimumInputLength: 3,
    ajax: {
      dataType: &quot; , &quot;'&quot; , &quot;json&quot; , &quot;'&quot; , &quot;,
      delay: 1000,
      url: poly_url,
      data: function (params) {
        var query = {
          q: params.term
        };
        return query;
      },
      processResults: function (data) {
        if (data.error){
          Materialize.toast(&quot;Koneksi Bermasalah&quot;, 3000);
          return false;
        }
        return {
          results: data.poly
        };
      },
    },
  });

  $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).on(&quot; , &quot;'&quot; , &quot;select2:select&quot; , &quot;'&quot; , &quot;, function (e) {

          $(&quot; , &quot;'&quot; , &quot;#poly&quot; , &quot;'&quot; , &quot;).val(e.params.data.text);

  });

})


                        
                    
                        
                            
    Nama_pasien*

    




  Peentar.executeLater(function(){
  Peentar.Materialize.refreshForm($(&quot; , &quot;'&quot; , &quot;form&quot; , &quot;'&quot; , &quot;));
  var poly_url = $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).data(&quot; , &quot;'&quot; , &quot;url&quot; , &quot;'&quot; , &quot;);
  $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).select2({
    minimumInputLength: 3,
    ajax: {
      dataType: &quot; , &quot;'&quot; , &quot;json&quot; , &quot;'&quot; , &quot;,
      delay: 1000,
      url: poly_url,
      data: function (params) {
        var query = {
          q: params.term
        };
        return query;
      },
      processResults: function (data) {
        if (data.error){
          Materialize.toast(&quot;Koneksi Bermasalah&quot;, 3000);
          return false;
        }
        return {
          results: data.poly
        };
      },
    },
  });

  $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).on(&quot; , &quot;'&quot; , &quot;select2:select&quot; , &quot;'&quot; , &quot;, function (e) {

          $(&quot; , &quot;'&quot; , &quot;#poly&quot; , &quot;'&quot; , &quot;).val(e.params.data.text);

  });

})


                        
                    
                        
                            
    Nama obat*

    




  Peentar.executeLater(function(){
  Peentar.Materialize.refreshForm($(&quot; , &quot;'&quot; , &quot;form&quot; , &quot;'&quot; , &quot;));
  var poly_url = $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).data(&quot; , &quot;'&quot; , &quot;url&quot; , &quot;'&quot; , &quot;);
  $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).select2({
    minimumInputLength: 3,
    ajax: {
      dataType: &quot; , &quot;'&quot; , &quot;json&quot; , &quot;'&quot; , &quot;,
      delay: 1000,
      url: poly_url,
      data: function (params) {
        var query = {
          q: params.term
        };
        return query;
      },
      processResults: function (data) {
        if (data.error){
          Materialize.toast(&quot;Koneksi Bermasalah&quot;, 3000);
          return false;
        }
        return {
          results: data.poly
        };
      },
    },
  });

  $(&quot; , &quot;'&quot; , &quot;.poly_select2&quot; , &quot;'&quot; , &quot;).on(&quot; , &quot;'&quot; , &quot;select2:select&quot; , &quot;'&quot; , &quot;, function (e) {

          $(&quot; , &quot;'&quot; , &quot;#poly&quot; , &quot;'&quot; , &quot;).val(e.params.data.text);

  });

})


                        
                    
                        
                            

TANGGAL RESEP




                        
       
 








  $(document).ready(function() {
      Peentar.datePicker(&quot;.datepicker&quot;);
  });







Jenis Resep



Resep Obat



Resep Optik










Obat Non-Racik

Obat Racik





Nama Obat







Item Penjamin






Jumlah



Harga Total (Rp)




Stok



Satuan



Harga Satuan (Rp)



Jumlah Resep



Jumlah Ambil



Harga (Rp)



Signa 1



Signa 2



JHO



Catatan




Cost Sharing




















Simpan









Racikan 1
KAPSUL
PUYER
SALEP
LARUTAN LUAR
LARUTAN DALAM
SUPPOSITORIA
BEDAK


Jumlah Racikan Resep




Jumlah Ambil Resep




Signa 1



Signa 2



JHO



Embalase (Rp)




Catatan




+ Obat









Nama Obat





delete



Item Penjamin





Jumlah




Harga Total (Rp)





Stok



Satuan




Harga Satuan (Rp)




Kekuatan Obat



Dosis Resep



Jumlah Resep




Jumlah Ambil




Harga (Rp)




Cost Sharing




SIMPAN



  function validateDecimal(e) {
    var t = e.value;
    e.value = (t.indexOf(&quot;.&quot;) >= 0) ? (t.substr(0, t.indexOf(&quot;.&quot;)) + t.substr(t.indexOf(&quot;.&quot;), 3)) : t;
  }








Nama Item






Stok



Kuantitas



Satuan



Harga (Rp)



Harga Total (Rp)

















Simpan








Daftar Produk


Preview Resep




  
    


    
        
        
        Belum memilih obat
    

  


  Total Harga Resep:
  Rp0




Batal


Lanjutkan



&quot;))]</value>
      <webElementGuid>3b746ed5-1556-4962-9a55-e4f19f48b9eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
