<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_not_interested_normal</name>
   <tag></tag>
   <elementGuidId>2b0efc24-0112-48a8-9d37-ba271be30112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pos_expres']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.normal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fcad19b0-0dbc-4dea-ab42-ff78086492ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>15d3c068-fec3-4187-b3c6-6563794cdd2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/home-v3/pos-f488790fa5a479cdaf87d30a61767151f80297d85a8f45342cdeed09141db861.png</value>
      <webElementGuid>d4195459-d6c9-4e95-9832-634fbf0d067a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pos_expres&quot;)/div[@class=&quot;menu&quot;]/img[@class=&quot;normal&quot;]</value>
      <webElementGuid>4ddfa6f1-300b-4e8e-8e67-05d95970cd06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='pos_expres']/div/img</value>
      <webElementGuid>b5c3e500-d744-44b9-a051-21b333ba7f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>2e61f0f4-ad6d-465a-a933-60d2b8710e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/home-v3/pos-f488790fa5a479cdaf87d30a61767151f80297d85a8f45342cdeed09141db861.png']</value>
      <webElementGuid>9fbcf246-0644-487e-a871-8616ef609b78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
