<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tambah Lain-lain_normal</name>
   <tag></tag>
   <elementGuidId>8f100a8b-cda4-447b-bcb4-85b78719a585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-modal']/div/div/div[2]/div/div[2]/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ff52458f-68eb-4353-af7b-25e60edb97b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>b0c3e774-219b-47b6-bab4-9cd330b3d804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-add-prescription-by-id</name>
      <type>Main</type>
      <value>data-add-prescription-by-id</value>
      <webElementGuid>85857536-2339-4c43-9164-8d51bea3d5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/cashier-pos/pembelian_resep-79f1548ea34623fa2d171cbfd5b85e3ba6f6b0f580fa8427b2703631144b8944.png</value>
      <webElementGuid>d8f04a59-40db-405d-a52d-774b7f9fc256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-modal&quot;)/div[1]/div[@class=&quot;submenu-pos&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;row set-bottom&quot;]/div[@class=&quot;col s6 center-align&quot;]/a[1]/div[@class=&quot;menu center&quot;]/img[@class=&quot;normal&quot;]</value>
      <webElementGuid>ccabdbd9-4479-4fe3-a590-d7607d849d3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-modal']/div/div/div[2]/div/div[2]/a/div/img</value>
      <webElementGuid>91fcae52-ff84-4cb6-88db-107970254c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/img</value>
      <webElementGuid>9316a7d9-2882-4953-a0e7-7fb7090db9a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/cashier-pos/pembelian_resep-79f1548ea34623fa2d171cbfd5b85e3ba6f6b0f580fa8427b2703631144b8944.png']</value>
      <webElementGuid>66534505-7fca-4a3f-a34d-50ed11c385fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
