<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_not_interested_normal</name>
   <tag></tag>
   <elementGuidId>2b0efc24-0112-48a8-9d37-ba271be30112</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pos_expres']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.normal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6aaa2f30-5a03-43b0-9322-a9444e5582ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>normal</value>
      <webElementGuid>03b8fc0f-6757-46ab-a723-3054d2ac60c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/assets/home-v3/pos-f488790fa5a479cdaf87d30a61767151f80297d85a8f45342cdeed09141db861.png</value>
      <webElementGuid>0eea2d00-76ad-42d2-b36e-9caceeb18ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pos_expres&quot;)/div[@class=&quot;menu&quot;]/img[@class=&quot;normal&quot;]</value>
      <webElementGuid>4b519aa5-a075-440c-a616-eaba71a83533</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='pos_expres']/div/img</value>
      <webElementGuid>9fc7db4d-bf68-41cc-a18c-83cada83a608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>e9ef2b45-87ba-4b04-bcbe-008cc3fac49f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/assets/home-v3/pos-f488790fa5a479cdaf87d30a61767151f80297d85a8f45342cdeed09141db861.png']</value>
      <webElementGuid>8abb179c-2aec-4999-869a-84c626bfec53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
