<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat Dokter Praktik_prescriptiondoc_b467a8</name>
   <tag></tag>
   <elementGuidId>2abd8c34-40ab-4d71-a2fe-37f88e5986d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prescription-doctor-address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prescription-doctor-address</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcba3abd-0b87-42f6-90f5-fc1870626c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prescription-doctor-address</value>
      <webElementGuid>46a3e2f3-0e1e-4a39-88ac-3fd4eb1f34a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required-input</value>
      <webElementGuid>623c9aa1-0b07-40cb-b74d-3d92c62dbaf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>618eb233-d141-42e9-a60e-087cae3c5e42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prescription[doctor_address]</value>
      <webElementGuid>579bc399-5271-44a8-b6d3-90b1f36d7c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prescription-doctor-address&quot;)</value>
      <webElementGuid>9e70ede3-82cf-4f12-bed2-2f5692be9b3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prescription-doctor-address']</value>
      <webElementGuid>765088c6-abfd-4f1c-a1c3-c35eb73ba215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prescription-data']/div[3]/div[4]/input</value>
      <webElementGuid>5d0fc7d8-1f98-4477-b00a-43bf4749f093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>b5baa439-e9d0-459a-8ea3-3ec609206631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'prescription-doctor-address' and @type = 'text' and @name = 'prescription[doctor_address]']</value>
      <webElementGuid>3cec67af-43dc-4470-bb0e-722c0b6c19e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
