<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PPK Asal_prescription-ppk-origin-name-search</name>
   <tag></tag>
   <elementGuidId>2476b8d6-0cec-4f4e-b82b-0b86b968e3ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prescription-ppk-origin-name-search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prescription-ppk-origin-name-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95a79149-7a0f-412e-a3dc-e1b2ea17e2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12fa7241-3c4e-4e0c-86bf-5f0f8f313f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prescription-ppk-origin-name-search</value>
      <webElementGuid>12a63216-a1ca-446f-9787-f5e6126c1574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prescription-ppk-origin-name-search</value>
      <webElementGuid>85f0800d-e498-4ad0-9a7d-164e1db8de8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-ppk-origin</value>
      <webElementGuid>866f7fd4-a398-42c2-9013-94d2d9727624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prescription-ppk-origin-name-search&quot;)</value>
      <webElementGuid>a9d3578b-ea0c-4776-8cef-5e5456300949</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prescription-ppk-origin-name-search']</value>
      <webElementGuid>08c3f8e1-ad9c-4463-ba8c-cb3c6d70b54a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prescription-data']/div[3]/div[2]/input</value>
      <webElementGuid>42f512d3-59ac-4ec6-9072-3ec6808682e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div[2]/input</value>
      <webElementGuid>8ef26804-43ca-48eb-9569-15a948c35ac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'prescription-ppk-origin-name-search' and @id = 'prescription-ppk-origin-name-search']</value>
      <webElementGuid>c86b9ad5-64fb-4c1d-ab25-54e8b3b9bf4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
