<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ON HOLD_search-customer</name>
   <tag></tag>
   <elementGuidId>e98f0033-81cd-49ad-b59c-9f7ee8da4925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-customer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search-customer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e28e9ca-59a1-4361-8371-ae78df6345c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-customer</value>
      <webElementGuid>651e37a3-5995-4c0d-8696-2a0ca427cc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c63e0e4e-8cbf-4f65-a7fc-3eca0f08b439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kimia Farma Nasional</value>
      <webElementGuid>57fac2a8-2bd8-4974-8ad7-4f6faaae2a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>745892a3-928e-44d6-85d3-08dc10d54986</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return event.keyCode != 13;</value>
      <webElementGuid>8d636886-97c5-473f-b0f7-e7a7b24e6207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-customer&quot;)</value>
      <webElementGuid>1a057ed3-2736-4bab-b949-f7f9da6f042a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-customer']</value>
      <webElementGuid>e20b271f-e045-4041-b162-4c0665d43576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home']/div/div/div[2]/div/nav/div/form/div/div/input</value>
      <webElementGuid>675da0d4-a56e-4afb-bf7c-d05f23d35ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>fbc66655-92e8-4b8e-be3c-b0cad369680c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search-customer' and @placeholder = 'Kimia Farma Nasional' and @type = 'search']</value>
      <webElementGuid>10a9a3a6-18b8-41e8-8f50-39e7d8176d8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
