<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sesi kasir sebelumnya masih aktif, si_096827</name>
   <tag></tag>
   <elementGuidId>e77bdf6b-74df-4bb3-91fc-06e26769aeda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cashier_session_bank_store']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cashier_session_bank_store</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e689781-ee31-4e50-a827-f31cce42e8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>bba247bc-7b49-4f56-8ddd-e35fd15761a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>format_currency</value>
      <webElementGuid>1d01b263-4864-4250-bf4d-e3a0c084edfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db020b48-0056-4103-ba8d-20775ecad9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cashier_session[bank_store]</value>
      <webElementGuid>bea6b156-d0a4-45d1-bd82-3c01c55c8d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cashier_session_bank_store</value>
      <webElementGuid>8f79caf8-7fc4-4700-94ed-5ac8b64b1c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cashier_session_bank_store&quot;)</value>
      <webElementGuid>b16f5797-0544-4f1a-a4b3-11c843995d23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cashier_session_bank_store']</value>
      <webElementGuid>9fe91000-2bf9-478c-9238-0d4355ce1dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5320']/div[2]/div/div/input</value>
      <webElementGuid>b71a03b7-62d4-4210-a02a-9f4d5ee266fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>8910d2d7-3afe-4dd0-b520-87e666058354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cashier_session[bank_store]' and @id = 'cashier_session_bank_store']</value>
      <webElementGuid>1adc3492-5e4e-44f8-a155-417cd5a2c93b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
