<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apakah Anda yakin akan mengakhiri ses_8216ad</name>
   <tag></tag>
   <elementGuidId>5c43d508-bd60-451d-99a3-d9b63ecb9c7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cashier_session_bank_store']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cashier_session_bank_store</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3358ae7a-e570-4969-b8c1-4632aeaf63c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>f9997dcc-7870-49c4-8426-a7787d333a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>format_currency</value>
      <webElementGuid>669c949d-d7dd-402c-960c-c8d485b60350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>061a2b81-2d50-4d33-b270-482fa29a125d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cashier_session[bank_store]</value>
      <webElementGuid>ee418f2f-b94d-492a-a8b5-e7c1719162f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cashier_session_bank_store</value>
      <webElementGuid>6d9e1d98-a441-4319-926a-53c5ec8a477c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cashier_session_bank_store&quot;)</value>
      <webElementGuid>9200c6cf-2aab-4bf6-9435-f06fd2ba51da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cashier_session_bank_store']</value>
      <webElementGuid>3db38228-d883-46f7-9459-23a0eda78e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5326']/div[2]/div/div/input</value>
      <webElementGuid>77447d84-4fb7-4e1e-af38-7e63fb097724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/form/div[2]/div/div/input</value>
      <webElementGuid>67525243-bf08-4cca-bffc-0760a58e835d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cashier_session[bank_store]' and @id = 'cashier_session_bank_store']</value>
      <webElementGuid>f9b8ab54-cb5a-4498-a940-f119537b1879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5317']/div[2]/div/div/input</value>
      <webElementGuid>1a502e0e-545f-4984-9961-e2e63f510b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5313']/div[2]/div/div/input</value>
      <webElementGuid>b82126b8-3d23-4731-9faf-beddbf41a12d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5308']/div[2]/div/div/input</value>
      <webElementGuid>536ec497-a7c3-4301-b2b7-28c9762428e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
