<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Uang (Rp)_paymentamount</name>
   <tag></tag>
   <elementGuidId>be8d0972-ebf9-4219-8486-6a0b56c32c77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment-amount-cash']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-amount-cash</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>219c4645-877e-4ceb-9590-a49952be6fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment-amount</value>
      <webElementGuid>b91b897e-3dfd-4e58-a855-237936aa6428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-amount-cash</value>
      <webElementGuid>8619ff5a-0a85-4d20-a8d8-d1fb2a2835dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8f5181d9-5778-4d21-b208-800d0c6b1cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84bdfd95-8f60-478c-9243-9788df1c55ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment[amount]</value>
      <webElementGuid>9b3b89ac-4233-4f0e-aa85-a7f4511aaa6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-amount-cash&quot;)</value>
      <webElementGuid>9b6d12c2-d1d9-486a-aba5-7586295c1aa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment-amount-cash']</value>
      <webElementGuid>9d81a635-7c1a-465c-a1b0-65a5ec7be8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-cash-method']/div/div/input</value>
      <webElementGuid>0d6dd6af-bac0-45ba-9dc2-354d1df3f707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/input</value>
      <webElementGuid>b48e8982-69e1-4aa9-87ec-209557aec5e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment-amount-cash' and @type = 'text' and @name = 'payment[amount]']</value>
      <webElementGuid>8fd99a71-b6c9-462b-9bf0-de7c61bad872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>e2477c43-c9dc-43b9-a7cc-973dbe3de880</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
