<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Telepon_prescriptionpatient_phone</name>
   <tag></tag>
   <elementGuidId>d1d5a152-84ac-4709-abbb-b9c98d1d09f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prescription_patient_phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prescription_patient_phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7413edde-8829-47de-ba8b-085e1c921735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required-input</value>
      <webElementGuid>c8492339-ba79-4275-8252-153415c83fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3381036c-f631-4caa-a118-6a1143ae7cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prescription[patient_phone]</value>
      <webElementGuid>ccf2f4fb-611a-4466-ac05-e02e012a75bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prescription_patient_phone</value>
      <webElementGuid>b115a964-bfb9-4acf-aa92-7d183ee91a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prescription_patient_phone&quot;)</value>
      <webElementGuid>ea81d7a1-95dc-47d6-afe5-1e285a9c058d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prescription_patient_phone']</value>
      <webElementGuid>0caaaed9-45a0-4edf-bb5a-85207dcfe0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prescription-data']/div/div[2]/input</value>
      <webElementGuid>0a5edf5a-878a-4896-8795-544248e9b11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>9588adb6-8803-4765-9f68-329bce0b6ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'prescription[patient_phone]' and @id = 'prescription_patient_phone']</value>
      <webElementGuid>baa171a3-03cf-4192-aedd-829378b746e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
