<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Transaksi  18068T1-111EY0018068_e0df95</name>
   <tag></tag>
   <elementGuidId>2cc4eb2c-5667-471d-9329-359f8fd5e62a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-product']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search-product</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>13853da1-ec40-4db0-9e3b-17b731b53c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-product</value>
      <webElementGuid>75c946b0-5e54-4b61-9fb3-b00931902369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Obat...</value>
      <webElementGuid>d4d9e7b1-6a6d-42fa-a4e6-0c2c3bc02285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>6b6cfdcc-436f-4b1c-be2d-742da650762b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-product&quot;)</value>
      <webElementGuid>43959192-4ab5-4494-8a25-4586fea40325</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-product']</value>
      <webElementGuid>03aa6c40-8adb-4165-baae-a6400e199fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home']/div/div/div/div/nav/div/form/div/input</value>
      <webElementGuid>7fa9d3bf-8f51-48cf-b568-57811c6c31dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>0c0ce626-3bb6-4b6b-93c0-1585b40ac59a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search-product' and @placeholder = 'Cari Obat...' and @type = 'search']</value>
      <webElementGuid>63ac6dfe-fe64-4055-9cf8-ce2bfa228912</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
