<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Poli_prescription-poly-name-search</name>
   <tag></tag>
   <elementGuidId>98f73ac7-c980-4243-ae36-ef2c0d449dae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prescription-poly-name-search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prescription-poly-name-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8ff3ed3-a8c0-4d50-8660-1845d40b7213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3cc8dcbc-8a4d-4748-a808-e2bd49e5acc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prescription-poly-name-search</value>
      <webElementGuid>a98862cf-4276-45af-951b-def4cefc9d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prescription-poly-name-search</value>
      <webElementGuid>7d0c503c-94d3-4840-a4fd-72d3a9c72a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-poly</value>
      <webElementGuid>4b82babf-7ac7-48b1-97d9-9281171fe53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prescription-poly-name-search&quot;)</value>
      <webElementGuid>5846f103-69a0-40d8-9bee-bd14e37b04ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prescription-poly-name-search']</value>
      <webElementGuid>b57bb02c-c3ae-4836-80bb-d33bf217e0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prescription-data']/div[3]/div[3]/input</value>
      <webElementGuid>9cab36d3-21ec-460a-ac9e-99db80351800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>43e0571d-b7c0-4cce-b3d2-1664ea52e96d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'prescription-poly-name-search' and @id = 'prescription-poly-name-search']</value>
      <webElementGuid>278f8f77-8348-4aee-b4dc-18d08b78474f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
