<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Peserta_insurance_member_name</name>
   <tag></tag>
   <elementGuidId>d554704f-8680-4329-9fe8-43c02d6c96f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='insurance_member_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#insurance_member_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>788c3ea5-32d5-4ff0-aa09-300426d695b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd1e7b1c-04fe-4aba-a3f5-ed50d920daee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>insurance_member_name</value>
      <webElementGuid>3ec3d1ae-6eda-4808-9a6c-4642bb98958b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>insurance_member_name</value>
      <webElementGuid>cf541486-9793-4af2-afb0-ab8b294430b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>6e1d0ccf-b320-4a72-b8b6-28fe63142d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>InvalidMsg(this)</value>
      <webElementGuid>735234a8-1941-418f-b8cf-2a6e1fbc51dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>DeleteInvalidMsg(this)</value>
      <webElementGuid>c58101a0-31a3-4992-898d-44851b20754a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;insurance_member_name&quot;)</value>
      <webElementGuid>95826be0-6c4c-41c0-86ae-7f3a0d7f83fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='insurance_member_name']</value>
      <webElementGuid>4f2c9af7-1056-4e20-ae02-782514228513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prescription-data']/div[4]/div/div[2]/input</value>
      <webElementGuid>5c4962b9-619a-41e9-8c1e-01233ee3dd52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>f69c09a6-cb73-4995-a1d1-c80d26dd4475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'insurance_member_name' and @id = 'insurance_member_name']</value>
      <webElementGuid>744a9eac-aa65-4cf9-8bc7-6b60c06405f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
