<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Silakan Masukkan Jumlah Modal Kasir_p_7892c4</name>
   <tag></tag>
   <elementGuidId>338cf6d8-dba9-4107-8075-4860ceb7c0dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='petty_cash']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#petty_cash</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c6eb0ba-ca80-4569-b9ca-4058bac48785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4939fbf-86d7-450d-93e3-00f5a2b5e025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>petty_cash</value>
      <webElementGuid>d365264c-8897-4481-b02f-5170f327eeb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>petty_cash</value>
      <webElementGuid>91a8cd58-d4d3-4917-9c57-7f6f8a755c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;petty_cash&quot;)</value>
      <webElementGuid>3b1fe3d1-d07e-4c0d-a345-124113d707bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='petty_cash']</value>
      <webElementGuid>f2a345d9-969b-4ca1-972e-1a1333cb268d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-modal']/div/form/div/div[2]/div/input</value>
      <webElementGuid>040d834e-cf6d-424d-b027-60fc7dc6de38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>126a0431-62d0-47e6-864b-fb161e2d5467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'petty_cash' and @id = 'petty_cash']</value>
      <webElementGuid>5e61c142-7cf5-474b-b5fb-144e6c56277e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
