<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Pemilik Kartu_paymentcard_holder_name</name>
   <tag></tag>
   <elementGuidId>522a5173-3c41-404e-a4f0-0cc33edc73e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment-owner-card']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-owner-card</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33bb23fa-b3d3-42a6-86fb-b97eb98a573c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-owner-card</value>
      <webElementGuid>b1e7b8e3-104a-414b-bfe5-5006a16ee732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f87c4fc-2083-4acf-8056-d3cd2c75e2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment[card_holder_name]</value>
      <webElementGuid>d18e38f9-d6f1-41e3-aa87-bcbc92ace9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-owner-card&quot;)</value>
      <webElementGuid>73566607-a47d-421e-9cfd-1fed97e62435</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment-owner-card']</value>
      <webElementGuid>b8cc2285-864c-4b26-b37b-41d8947e27f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-card-method']/div[2]/div/input</value>
      <webElementGuid>fbbbe93c-054b-4a2d-bd7c-44458cacf1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>f1172681-0aad-4629-9d3a-0ac1b3000170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment-owner-card' and @type = 'text' and @name = 'payment[card_holder_name]']</value>
      <webElementGuid>295edbc7-24b1-423f-bf92-b587d614ba08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
