<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Signa 1_non_dispensed_drugsigna1</name>
   <tag></tag>
   <elementGuidId>113e2983-ef46-4799-b970-23cbd9643cc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='non-dispensed-drug-signa1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#non-dispensed-drug-signa1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d8382ba-8bff-4450-a03e-e8117b2bff55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>non-dispensed-drug-signa1</value>
      <webElementGuid>688666a3-27e7-4456-b977-c60cae6c989d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>non-dispensed-drug-field</value>
      <webElementGuid>6cd62ecf-0e62-475a-8745-94a8b08939c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>87cdd5ee-1d01-49e5-9e13-3fe4e18b5554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>non_dispensed_drug[signa1]</value>
      <webElementGuid>f6df4cf5-59e8-4fda-a1ac-cf78b7686e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;non-dispensed-drug-signa1&quot;)</value>
      <webElementGuid>2779123c-b8bb-477b-bb87-384d88b460e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='non-dispensed-drug-signa1']</value>
      <webElementGuid>65d66d26-4a79-43dd-ab2c-52a4ce4ecbca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-non-disp']/div/div[9]/input</value>
      <webElementGuid>d7f2993b-d12f-44d4-b07f-7e8ebc3387fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>f4d7b596-d052-4037-8961-4bcabe3eb723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'non-dispensed-drug-signa1' and @type = 'text' and @name = 'non_dispensed_drug[signa1]']</value>
      <webElementGuid>3cd04e3c-1346-42c1-ba12-83656f4b76ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
