<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Kartu_paymentcard_number</name>
   <tag></tag>
   <elementGuidId>a7410a05-f9c4-45f8-8347-f39733237c77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment-number-card']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-number-card</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d60a373-eaa2-43ce-8312-bf6d9c203131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-number-card</value>
      <webElementGuid>780a8b3f-64b5-4780-bf9f-3abb0b27f557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca6bd514-8539-46cb-b8af-1c7366c49877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment[card_number]</value>
      <webElementGuid>73c776ff-4782-4f6b-8c3e-4d38dd213b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-number-card&quot;)</value>
      <webElementGuid>865afa71-6642-4131-9a0e-6e3246f2f96e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment-number-card']</value>
      <webElementGuid>6bcd275d-cb53-4b26-914f-471bacc28391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-card-method']/div[2]/div[2]/input</value>
      <webElementGuid>05d7ba75-0584-4c24-8d89-5fb6051baea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>1753024b-15fc-44ff-832d-c1eb3d1d264d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment-number-card' and @type = 'text' and @name = 'payment[card_number]']</value>
      <webElementGuid>91533072-40c8-4b66-8b36-0d1127f362d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
