<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Npp_attempt222answer_text</name>
   <tag></tag>
   <elementGuidId>a5b8e32a-4115-4c24-bfce-914e9d16d484</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='004']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#004</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>670359d9-3a59-4d76-9617-5351dcd5ed9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>10db69f3-55c7-4c4a-affc-d71568085736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>InvalidMsg(this)</value>
      <webElementGuid>01ca2194-feec-43e0-86cd-4c23275c55d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>004</value>
      <webElementGuid>798eb3b6-e28d-495f-b35b-eae5573fbb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>323f652f-2bb6-499b-a056-02fa18405479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attempt[222][answer_text]</value>
      <webElementGuid>7141a161-4a2c-4d76-94a0-7068f044e315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>DeleteInvalidMsg(this)</value>
      <webElementGuid>179f3cce-fde3-4c70-83a0-aa136146941e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;004&quot;)</value>
      <webElementGuid>b8c51525-4f94-40c5-a6d7-f71d56393e42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='004']</value>
      <webElementGuid>cc391917-a089-440a-a765-401f8e27e1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prescription-data']/div[4]/div/div[4]/div/input</value>
      <webElementGuid>1472ca35-0a13-465c-bfda-e1ac395c561a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[4]/div/input</value>
      <webElementGuid>85016d89-9715-4e5c-aa14-4d1687658993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '004' and @type = 'text' and @name = 'attempt[222][answer_text]']</value>
      <webElementGuid>ec7b9005-619c-4d44-97b1-a29c6f63fdcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
