<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nominal (Rp)_debit_credit_amount</name>
   <tag></tag>
   <elementGuidId>d0d277a8-a3d7-4961-8246-bf0de5418135</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment-amount-card']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-amount-card</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4898a6cc-10ae-4462-8fed-ea2126696d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment-amount</value>
      <webElementGuid>a8e4b9f9-3dfe-4a9d-b197-c219d4121d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-amount-card</value>
      <webElementGuid>69f7f2c6-c66b-4ade-aef1-e38d64f86183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>debit_credit_amount</value>
      <webElementGuid>7f6e275e-1003-4a0e-aeb2-16cbda176883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b307e217-4f06-4f2c-8bfa-8fcbe79e6d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>243adf6b-1e00-4515-b2d5-7db203b22c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-amount-card&quot;)</value>
      <webElementGuid>a3bd38e5-4308-4224-bedb-fc6ae3676785</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment-amount-card']</value>
      <webElementGuid>e0f82968-320b-4b1b-9172-7483a6004709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-card-method']/div[4]/div/input</value>
      <webElementGuid>255f5fc9-843a-415f-bfb6-f04969e0da38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[4]/div/input</value>
      <webElementGuid>c2895e29-e734-44e8-a02f-7e650d9a0476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment-amount-card' and @name = 'debit_credit_amount' and @type = 'text']</value>
      <webElementGuid>54b39f82-f9f2-4098-8c0a-c06732b657af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
