<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Pasien_prescriptionpatient_name</name>
   <tag></tag>
   <elementGuidId>0350a39d-cfa1-486c-a053-9d4df323bdbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prescription_patient_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prescription_patient_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df0e1b15-6b3d-43d6-b514-d9dc7615a64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required-input</value>
      <webElementGuid>05d1287f-5d15-420b-88e3-2b571bf5248c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ed70aa3-09de-47b6-b164-ea7e74f77584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prescription[patient_name]</value>
      <webElementGuid>d229160a-16d1-45a7-a26a-df36d5105642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prescription_patient_name</value>
      <webElementGuid>2680516e-3b7f-4ffb-aafa-1c5237df367f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prescription_patient_name&quot;)</value>
      <webElementGuid>32213641-1730-4d87-9c4d-61817ad3141e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prescription_patient_name']</value>
      <webElementGuid>f45127a0-ea98-47a4-bb54-73ed4868fb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prescription-data']/div/div/input</value>
      <webElementGuid>15734793-f4cc-4c13-a9c9-2d9a9808e6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>5e91840f-079a-473b-b697-875a0d8ae57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'prescription[patient_name]' and @id = 'prescription_patient_name']</value>
      <webElementGuid>c1204f4b-531f-4c43-b2d3-c1d936bbb647</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
