<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Apakah Anda yakin akan mengakhiri ses_8216ad</name>
   <tag></tag>
   <elementGuidId>5c43d508-bd60-451d-99a3-d9b63ecb9c7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cashier_session_bank_store']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cashier_session_bank_store</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d264b60-25fc-460f-a8fe-5e7c351cfdb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>2ba670c5-dc72-4955-9f99-83df8ce84044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>format_currency</value>
      <webElementGuid>22667800-099a-4e9c-94f4-11f9f8d620ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dbbda64f-86d3-4364-898e-96a7f4b4b6a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cashier_session[bank_store]</value>
      <webElementGuid>adf721bf-46ee-47ac-a79e-55b4c7ea70d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cashier_session_bank_store</value>
      <webElementGuid>b9d4e0f6-3196-4aab-b268-76a29e3f028c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cashier_session_bank_store&quot;)</value>
      <webElementGuid>061c98d3-ec54-4ba7-a078-97244598dc53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cashier_session_bank_store']</value>
      <webElementGuid>adf13511-7bdf-4f7c-a4b9-991195e9d040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5337']/div[2]/div/div/input</value>
      <webElementGuid>b77f83e9-a98a-412b-8f6a-851f537eb467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/form/div[2]/div/div/input</value>
      <webElementGuid>a4d8865c-6203-475d-a0b0-0f5458bcdbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cashier_session[bank_store]' and @id = 'cashier_session_bank_store']</value>
      <webElementGuid>9e9a479d-ace1-417b-8139-33e95516d0b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5333']/div[2]/div/div/input</value>
      <webElementGuid>7c66b02b-3524-4686-ad5c-d2810678d38b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5330']/div[2]/div/div/input</value>
      <webElementGuid>e125dbf3-de57-4f9a-bf26-32f29f21c1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5326']/div[2]/div/div/input</value>
      <webElementGuid>77447d84-4fb7-4e1e-af38-7e63fb097724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5317']/div[2]/div/div/input</value>
      <webElementGuid>1a502e0e-545f-4984-9961-e2e63f510b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5313']/div[2]/div/div/input</value>
      <webElementGuid>b82126b8-3d23-4731-9faf-beddbf41a12d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_cashier_session_5308']/div[2]/div/div/input</value>
      <webElementGuid>536ec497-a7c3-4301-b2b7-28c9762428e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
