<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_order_item_quantity</name>
   <tag></tag>
   <elementGuidId>d65f5c5c-d240-4756-a4a3-4c850de9b6ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='order_item_quantity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#order_item_quantity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>455a4270-392f-4cb6-8a21-864dc5a30c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>order_item_quantity</value>
      <webElementGuid>650de475-fd40-4190-b104-a47aa472f31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>order_item_quantity</value>
      <webElementGuid>fb45bc2e-1f7e-45e8-abe4-a07f0c622c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ad371db7-abb1-460d-9223-8bfe034f5734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oi_quantity right-align shadow</value>
      <webElementGuid>dacad8d6-0d62-4751-8301-4c291952bd1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2bb19767-c85a-4026-92e9-fd665e32e563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>edit-quantity-url</name>
      <type>Main</type>
      <value>/pos_expres/order/18068/edit_item/9596/false</value>
      <webElementGuid>3d054925-a428-4b79-bc79-decb8efc2c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>order_item_id</name>
      <type>Main</type>
      <value>9596</value>
      <webElementGuid>967c2e44-e3fa-4099-8067-3c0dd815a07c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>status</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ae0ff3e7-c0a5-4b8b-bbdc-409201f67456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shadow_stock_id</name>
      <type>Main</type>
      <value>225655</value>
      <webElementGuid>fc08a81a-f5b6-4e4f-8d38-9ea95df46b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>item_id</name>
      <type>Main</type>
      <value>140207053</value>
      <webElementGuid>ac97e26b-6f50-4439-8e33-7d07a098b09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>item_shadow_id</name>
      <type>Main</type>
      <value>15331</value>
      <webElementGuid>ac931734-6451-4ad6-b1d7-8aa75fd5bdb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max_quantity</name>
      <type>Main</type>
      <value>9949</value>
      <webElementGuid>e41affe3-c9e5-4c15-9b8a-6e3d60301dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order_item_quantity&quot;)</value>
      <webElementGuid>bf37398e-542f-4ef2-b940-8db1db71e8f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='order_item_quantity']</value>
      <webElementGuid>75c15b6c-1f55-4720-95d2-9bfa77f4ee9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-cart']/ul/div[2]/div/div[3]/input</value>
      <webElementGuid>4bc6b6eb-84e9-4fcd-a68c-b793dc2f8872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>ec77e135-4f95-40de-8d5d-1bf36d1cbce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'order_item_quantity' and @id = 'order_item_quantity']</value>
      <webElementGuid>0bf30cd6-5706-4fa6-a14e-51a5a0811ab8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
