<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Transaksi  18052T1-111EY0018052_2da39c</name>
   <tag></tag>
   <elementGuidId>b2e41730-5f8a-4a95-8340-6f7613ff3ff8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-product']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search-product</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0c03881-7324-4768-810a-eaeb01ecdd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-product</value>
      <webElementGuid>143b866a-53ea-40bb-aa6a-5e91786f8cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Obat...</value>
      <webElementGuid>b0f42ce8-141f-4eeb-a699-ce1fe5a990e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>6ceb281d-b805-4eb4-aa63-cd11b8fb8dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-product&quot;)</value>
      <webElementGuid>fc71e860-5bce-408f-a0b9-451da3e6b4c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-product']</value>
      <webElementGuid>4bd2b5b8-0c82-4bf8-8fe6-9bd614e89dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home']/div/div/div/div/nav/div/form/div/input</value>
      <webElementGuid>82926f06-533e-4443-bb90-a0551f24125e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>cc0c5902-a011-4bfd-9091-1a2cd5fbcc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search-product' and @placeholder = 'Cari Obat...' and @type = 'search']</value>
      <webElementGuid>f5e620b5-c1ef-4735-9071-a4a43f321a87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
