<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Signa 2_non_dispensed_drugsigna2</name>
   <tag></tag>
   <elementGuidId>362fa3a0-d990-485c-9458-114d6f65c868</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='non-dispensed-drug-signa2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#non-dispensed-drug-signa2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c42a972-7616-4e2e-87a2-00ccda9e9d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>non-dispensed-drug-signa2</value>
      <webElementGuid>aed7701b-7acb-47dd-a8fb-a7da001b1964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>non-dispensed-drug-field</value>
      <webElementGuid>f56dcaec-bb32-453c-bdc9-7d3806b3e1db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1933971a-2a6c-479a-b3b1-dee348095437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>non_dispensed_drug[signa2]</value>
      <webElementGuid>68cbcea3-e4eb-4c3b-ba36-c869f101ca33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;non-dispensed-drug-signa2&quot;)</value>
      <webElementGuid>f42cda87-8370-46a6-8c8a-91f39ade67ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='non-dispensed-drug-signa2']</value>
      <webElementGuid>b7b6a8fa-721f-4544-b63c-50343c818674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-non-disp']/div/div[10]/input</value>
      <webElementGuid>e95d7a9a-2298-413a-ac4c-3ffbd72adacd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>8895e11d-4a95-409c-b211-8307cc8e5265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'non-dispensed-drug-signa2' and @type = 'text' and @name = 'non_dispensed_drug[signa2]']</value>
      <webElementGuid>66ead27b-ae86-42bc-ab5b-769fa5d15b5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
