<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat Pasien_prescriptionpatient_address</name>
   <tag></tag>
   <elementGuidId>beaf5b05-2fc6-4fd4-9b12-ea27318d9e4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prescription_patient_address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prescription_patient_address</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90f66189-691a-46fc-8244-b01fb2747b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required-input</value>
      <webElementGuid>241dc854-6b4b-46bc-a97d-bfe5fef85638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c49948b-c4df-4de4-ace7-a0bbc6cfc639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prescription[patient_address]</value>
      <webElementGuid>f25074c8-7795-4a57-b66e-320874756285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prescription_patient_address</value>
      <webElementGuid>9fedab7c-9afd-49e7-ab96-d979d2442a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prescription_patient_address&quot;)</value>
      <webElementGuid>26c066c1-f8d0-4a4d-a628-a249fd9265b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prescription_patient_address']</value>
      <webElementGuid>a5d6ece0-5e23-4c94-a24c-3b8c7f227aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prescription-data']/div/div[3]/input</value>
      <webElementGuid>b304c025-57e1-4e8c-80bb-01b4f887bba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/input</value>
      <webElementGuid>e2005330-71d8-48cc-b99a-d89cc2f6b7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'prescription[patient_address]' and @id = 'prescription_patient_address']</value>
      <webElementGuid>dd3d17ef-1797-40ec-9fc5-98f1f6571214</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
