<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Obat_non-dispensed-drug-name-search</name>
   <tag></tag>
   <elementGuidId>30804314-b982-4dee-89d0-c8e01367c3bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='non-dispensed-drug-name-search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#non-dispensed-drug-name-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1d16feb-800d-4546-80bf-71b92a5170f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae7f6f2a-d46e-4fa8-819b-0bcb4ef7454e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>non-dispensed-drug-name-search</value>
      <webElementGuid>cc8ca975-5c26-42a0-8603-4154b94b9998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>non-dispensed-drug-name-search</value>
      <webElementGuid>70b5bf10-a7d3-441a-9aad-b0dc3dfd4e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-drug</value>
      <webElementGuid>f025595f-2491-42e7-8c30-e2b56f2cae62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan nama obat</value>
      <webElementGuid>d3b2419f-778c-4bf4-ad76-e2431a74cf31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;non-dispensed-drug-name-search&quot;)</value>
      <webElementGuid>779f61bc-b2ea-4a36-8a07-a4fb074b554f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='non-dispensed-drug-name-search']</value>
      <webElementGuid>02b864c9-ee98-4a7d-a07a-73e2bb72d7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-non-disp']/div/div/input</value>
      <webElementGuid>6789c243-bc30-49f4-b2e7-eb3d4e45d035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/div/input</value>
      <webElementGuid>d346b06f-01fb-410d-8be2-7b2bfe46f810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'non-dispensed-drug-name-search' and @id = 'non-dispensed-drug-name-search' and @placeholder = 'Masukkan nama obat']</value>
      <webElementGuid>e91e8024-8462-49ea-a2fa-8165fdb1e5e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
