<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Dokter_prescription-doctor-name-search</name>
   <tag></tag>
   <elementGuidId>d20d87c6-2f6a-4a89-9b16-4efe6cb98fe0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prescription-doctor-name-search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#prescription-doctor-name-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4eb2c2a-c5c3-41f8-94fd-62d821491532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b30c1fd5-0234-4ab3-9feb-455d76847333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>prescription-doctor-name-search</value>
      <webElementGuid>dcd18538-bed5-4c05-a4d0-8025edf9555b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prescription-doctor-name-search</value>
      <webElementGuid>e278ac95-5cd6-45fe-a097-48dc69aac633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-doctor</value>
      <webElementGuid>9b4dcbc0-c85d-4810-91be-0a22d931b79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prescription-doctor-name-search&quot;)</value>
      <webElementGuid>7bcf75a6-7b2b-413a-9b7c-fd6415a476b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prescription-doctor-name-search']</value>
      <webElementGuid>998b0f29-9286-4d15-9b87-77884212aa5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prescription-data']/div[3]/div/input</value>
      <webElementGuid>54949b07-2b33-4839-90f1-682a934a9513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/input</value>
      <webElementGuid>959fa1bd-99d4-4c8d-9a4c-8855aa42b0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'prescription-doctor-name-search' and @id = 'prescription-doctor-name-search']</value>
      <webElementGuid>65510af7-3f70-4054-a6a0-4ffd966bbee5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
