<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Transaksi  18062T1-111EY0018062_8606ef</name>
   <tag></tag>
   <elementGuidId>1a6020b4-b0e9-4c19-9746-8e0ba017d89f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-product']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search-product</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bce3daad-fc58-4d2f-b336-69b8d1275fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-product</value>
      <webElementGuid>e39d1101-c0be-4f16-9d8a-1fccf4b5500f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari Obat...</value>
      <webElementGuid>5b63b917-9f0e-4d4e-9392-6f322c0c953f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>423b49f6-1a8c-4b88-b8cf-662dabc00cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-product&quot;)</value>
      <webElementGuid>b206d0f0-5482-44da-8996-73986f6c238d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-product']</value>
      <webElementGuid>8be38d99-ab85-450f-bb3a-2d45783ae680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home']/div/div/div/div/nav/div/form/div/input</value>
      <webElementGuid>6e746954-2f0a-4ed3-8ce0-7abc49ba13ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>73cd8bf8-dbeb-4b31-a2a6-8576dad8a3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search-product' and @placeholder = 'Cari Obat...' and @type = 'search']</value>
      <webElementGuid>72b15267-9b50-44c5-bc22-3415c19f0a92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
