<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jumlah Resep_non-dispensed-drug-quant_6b7e69</name>
   <tag></tag>
   <elementGuidId>eeac11c6-01a4-442c-ac2a-b5b5c202b1fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='non-dispensed-drug-quantity-presc-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#non-dispensed-drug-quantity-presc-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18ee3bb4-bff5-4baf-b403-74292eac5489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec88c2d8-95f4-489c-853f-832640506380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>non-dispensed-drug-quantity-presc-input</value>
      <webElementGuid>602143e9-6cdb-476c-b79d-1c6edf0b0db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>non-dispensed-drug-quantity-presc-input</value>
      <webElementGuid>004f1a21-200e-4523-9d82-320ea3fd3059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;non-dispensed-drug-quantity-presc-input&quot;)</value>
      <webElementGuid>e1f13410-f720-4851-9ac6-117fe2381f6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='non-dispensed-drug-quantity-presc-input']</value>
      <webElementGuid>295a4a7e-ce5d-4986-846d-dab9e4a01e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-non-disp']/div/div[6]/input</value>
      <webElementGuid>4ce77ec2-2da6-4fc6-bfea-16689849993c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>c2b2e3c2-9377-410b-83c0-fdd6884ae558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'non-dispensed-drug-quantity-presc-input' and @id = 'non-dispensed-drug-quantity-presc-input']</value>
      <webElementGuid>635172e5-0a3f-4854-959f-9129fbf6edb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
