<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama_pasien_attempt250answer_text</name>
   <tag></tag>
   <elementGuidId>5187a623-62c5-4e25-aefc-91e1e3c7a8c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='034']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#034</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b2cbd26-ba38-4e95-b8fd-1fb88137e734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>f3bc17d4-7ed0-4991-b65a-ee4407d37815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninvalid</name>
      <type>Main</type>
      <value>InvalidMsg(this)</value>
      <webElementGuid>7465e0b5-b535-4c3f-83cd-636a1237c050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>034</value>
      <webElementGuid>9b03b69b-b71f-4571-9399-4e9870d131e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f937c28-2172-4397-a55e-f45c4928ce80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attempt[250][answer_text]</value>
      <webElementGuid>b919364f-e616-4611-a425-f87a8ced42a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>DeleteInvalidMsg(this)</value>
      <webElementGuid>b8a941bf-8e20-446f-95da-2de414baeaf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;034&quot;)</value>
      <webElementGuid>c66b6138-7bec-44fc-962d-50b23999baa4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='034']</value>
      <webElementGuid>25c0d209-b3e0-4559-9b37-84884130d37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prescription-data']/div[4]/div/div[5]/div/input</value>
      <webElementGuid>9ab13bb9-6fbd-4b15-9ce2-5b51c8939b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>9c28e4c8-0e9e-4fbf-8ccc-02a5829d67c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '034' and @type = 'text' and @name = 'attempt[250][answer_text]']</value>
      <webElementGuid>718e28a5-0dd3-43c9-b8aa-41bc015077e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
