<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ON HOLD_search-customer</name>
   <tag></tag>
   <elementGuidId>e98f0033-81cd-49ad-b59c-9f7ee8da4925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-customer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search-customer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>296f1f54-5b41-484d-a5f6-82df9f357776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-customer</value>
      <webElementGuid>ba34e6e6-2bc3-4a6b-ac02-3dd008e5e19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d4d86f28-1a3b-4b40-8b50-5db3f69b9b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kimia Farma Nasional</value>
      <webElementGuid>ce93b3ff-943b-49ca-8426-4c67679ded94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>6605c2c3-336b-4388-9cb3-613d7ab0ce35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return event.keyCode != 13;</value>
      <webElementGuid>f08e0194-4527-4718-bfb1-2a340e0a4185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-customer&quot;)</value>
      <webElementGuid>5ee429f7-2ef2-4991-b01b-3ab156b2dc23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-customer']</value>
      <webElementGuid>1a2c4850-d938-48fa-b5c6-a75234c09f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home']/div/div/div[2]/div/nav/div/form/div/div/input</value>
      <webElementGuid>10b5db5e-ce16-4b5f-8590-c4d9d2876c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/input</value>
      <webElementGuid>512318e8-45cd-4772-9f71-6b4cc59be039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search-customer' and @placeholder = 'Kimia Farma Nasional' and @type = 'search']</value>
      <webElementGuid>24a98d2c-c18e-4859-89e5-b2a8de99adc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
