<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Nama_pasien</name>
   <tag></tag>
   <elementGuidId>4014e64a-2a2c-4e65-9c68-04fb1d125186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='prescription-data']/div[4]/div/div[5]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>749dfc93-e3a7-446a-93a8-3ba795b419f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tosca</value>
      <webElementGuid>24f6930b-95e1-497c-a147-49c9c81e96c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>attempt_250_answer_text</value>
      <webElementGuid>2d1a1022-b7ee-4d9a-85d8-75ab92950568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama_pasien*</value>
      <webElementGuid>842573ef-5e12-4f7a-b3f3-6a5fcef22ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;prescription-data&quot;)/div[@class=&quot;row fill-form-expres&quot;]/div[@class=&quot;row insurance-form-fill&quot;]/div[@class=&quot;col s4&quot;]/div[@class=&quot;form-group&quot;]/label[@class=&quot;tosca&quot;]</value>
      <webElementGuid>a002b661-c08d-4d1d-ba55-87f115fedc6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prescription-data']/div[4]/div/div[5]/div/label</value>
      <webElementGuid>3fdd2bfe-d528-4424-8acf-3f5993c0aaa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Npp*'])[1]/following::label[1]</value>
      <webElementGuid>171e5c8a-e198-4ed7-a75b-2d167a764031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. resep*'])[1]/following::label[2]</value>
      <webElementGuid>ce11d3d2-b6c3-499f-b0bd-1215fc49057c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama obat*'])[1]/preceding::label[1]</value>
      <webElementGuid>c658c8b4-0f80-4e23-8d4c-dd085ecea80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TANGGAL RESEP'])[1]/preceding::label[2]</value>
      <webElementGuid>c3430916-9970-4de9-9345-db9ade585a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nama_pasien*']/parent::*</value>
      <webElementGuid>b9a8d620-cb6d-447b-a4c6-c12a6c66b283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/label</value>
      <webElementGuid>4e23f51d-d0b4-4d41-bae2-09d4f8808441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Nama_pasien*' or . = 'Nama_pasien*')]</value>
      <webElementGuid>90047d2c-6bd8-46bc-b0c5-2e7bda56033d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
