<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label</name>
   <tag></tag>
   <elementGuidId>c17bc973-68b6-4148-b216-ce55c9c96684</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment-detail']/table/tbody/tr/td[4]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c951c0e5-4cef-463b-a969-5fcb18a37145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>31517</value>
      <webElementGuid>9083baec-0f84-4692-85cd-d087e1402ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-detail&quot;)/table[@class=&quot;bordered&quot;]/tbody[1]/tr[1]/td[4]/label[1]</value>
      <webElementGuid>e17bf0c5-bd17-49f3-8e57-2a6107f877a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-detail']/table/tbody/tr/td[4]/label</value>
      <webElementGuid>289ee2b0-42b9-43a2-a1b5-3e533584359b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/label</value>
      <webElementGuid>c2657f31-8c1e-4ce0-b744-e82bc17d3884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-detail']/table/tbody/tr[2]/td[4]/label</value>
      <webElementGuid>63661db8-f7f6-4e8a-9b6b-388b37e652b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/label</value>
      <webElementGuid>626cb4df-308b-415a-9440-26ac8e9517b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
