<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Kredit Resep</name>
   <tag></tag>
   <elementGuidId>8688e987-2f3c-4300-89f3-1d757fb2a020</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='edit_prescription_3063']/div[3]/div/div[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>67015681-427f-4a7f-ab21-24c2534f2090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>presc_payment_kredit</value>
      <webElementGuid>d7b2a5a2-ccf0-49fc-b478-dba0d718bf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kredit Resep</value>
      <webElementGuid>d9f52144-ce4e-4ee5-a898-e0613be82c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edit_prescription_3063&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col s3 payment-method&quot;]/div[@class=&quot;input-field&quot;]/label[1]</value>
      <webElementGuid>546aa356-93c5-4280-aced-cc1b52ca3804</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_prescription_3063']/div[3]/div/div[2]/label</value>
      <webElementGuid>757ffa11-91ac-41bd-b786-4d6a567cf296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tunai'])[1]/following::label[1]</value>
      <webElementGuid>bb63b7eb-f769-4629-a2f2-9ce98dd36ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Metode Bayar'])[1]/following::label[2]</value>
      <webElementGuid>4ffc3cc9-6f71-430d-853a-f0d6d0d3bbea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-pilih jaminan-'])[2]/preceding::label[1]</value>
      <webElementGuid>346cb512-084e-4114-bca3-509befa2e97a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Pasien*'])[1]/preceding::label[1]</value>
      <webElementGuid>57acb24c-c859-4e84-b568-5ebd86b3b51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kredit Resep']/parent::*</value>
      <webElementGuid>10a44753-d4a7-469f-83a7-7225605ee160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/label</value>
      <webElementGuid>c693cbcf-abbd-4483-ab4e-241fd24a415f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Kredit Resep' or . = 'Kredit Resep')]</value>
      <webElementGuid>107aca80-fb53-4a7a-bee0-e7bd59fda5c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_prescription_3061']/div[3]/div/div[2]/label</value>
      <webElementGuid>f2e9d3a9-449e-4bd1-8c3d-16e18c5a0c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_prescription_3059']/div[3]/div/div[2]/label</value>
      <webElementGuid>960f1ba5-7c87-427c-b6a1-efa800aecd71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
