<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label</name>
   <tag></tag>
   <elementGuidId>c17bc973-68b6-4148-b216-ce55c9c96684</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment-detail']/table/tbody/tr/td[4]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>efb4e242-a7bc-4048-920e-60c8e78146c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>31517</value>
      <webElementGuid>8c0193c3-a1d9-42b2-ad39-832fb14ab189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-detail&quot;)/table[@class=&quot;bordered&quot;]/tbody[1]/tr[1]/td[4]/label[1]</value>
      <webElementGuid>4d7fc5b4-8375-4e1c-8cdc-58b1bea8b27d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-detail']/table/tbody/tr/td[4]/label</value>
      <webElementGuid>0081c64b-6cd9-40be-8b9a-17f0a141c427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/label</value>
      <webElementGuid>e5a4052f-96d3-48f1-a540-7c9210b2297d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-detail']/table/tbody/tr[2]/td[4]/label</value>
      <webElementGuid>63661db8-f7f6-4e8a-9b6b-388b37e652b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/label</value>
      <webElementGuid>626cb4df-308b-415a-9440-26ac8e9517b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
