<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Kartu Debit</name>
   <tag></tag>
   <elementGuidId>d1fa5ee3-e451-4764-9a5a-86d955a73a02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment-card-method']/div/div/label[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>cf0078e7-6286-4f9b-8143-93419e766446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>payment_card_type_debit</value>
      <webElementGuid>4a8c36e8-c8a1-4a68-bbea-f356fee0c205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kartu Debit</value>
      <webElementGuid>6af481a5-71de-4ee5-bb77-cf8a6bb6062d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-card-method&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col s12&quot;]/label[2]</value>
      <webElementGuid>d16a4bed-8cbe-4511-9722-0fe6baf7b661</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-card-method']/div/div/label[2]</value>
      <webElementGuid>00c2cfca-85f9-4d3a-a02f-b5300e26b29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kartu Kredit'])[1]/following::label[1]</value>
      <webElementGuid>e34f08e5-4792-4460-91a6-249195913866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Kartu'])[1]/following::label[2]</value>
      <webElementGuid>eb908dc4-4a38-411c-8d13-b48ef456a002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Pemilik Kartu'])[1]/preceding::label[1]</value>
      <webElementGuid>4d7af94b-836c-45e3-b083-3402732b64ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Kartu'])[1]/preceding::label[2]</value>
      <webElementGuid>2b65b190-7df4-4910-9cf1-0915ff8f0c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kartu Debit']/parent::*</value>
      <webElementGuid>981197ad-d249-481f-826f-b2e4adf91f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]</value>
      <webElementGuid>ace1535f-de40-45fd-925e-ca2f6f5f709f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Kartu Debit' or . = 'Kartu Debit')]</value>
      <webElementGuid>bbcdc6da-cf3e-4209-88b0-f21c01b95343</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
