<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_ADMEDIKA PAYOR PT-</name>
   <tag></tag>
   <elementGuidId>76254f81-928c-470a-8516-07c9f4fd2189</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-prescription_payment_insurance-result-dtkw-22042']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-prescription_payment_insurance-result-dtkw-22042</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>87d294b1-593c-4316-99f4-55a327443942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>2bbafbf5-30a4-4e2c-8173-f9077bb08896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-prescription_payment_insurance-result-dtkw-22042</value>
      <webElementGuid>730bd003-fc76-44b7-b03c-b42fc1166595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>c839827e-b13e-4d29-82fc-ea3821ef3535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>262dd5ec-3965-4085-af89-88905aebfceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADMEDIKA PAYOR PT- </value>
      <webElementGuid>f96702e0-e86b-4dbd-872c-6a689cefd84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-prescription_payment_insurance-result-dtkw-22042&quot;)</value>
      <webElementGuid>c0b78083-7cc1-4b22-a7f4-2d031f6a7518</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-prescription_payment_insurance-result-dtkw-22042']</value>
      <webElementGuid>0f6612f0-f522-402c-b2d6-09dba21fd6eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-prescription_payment_insurance-results']/li[3]</value>
      <webElementGuid>6bfb3b0e-4c9e-47a5-8c2d-3e4d4fcf25e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMEDIKA PAYOR PT-'])[4]/following::li[1]</value>
      <webElementGuid>d13a2043-9002-4ccf-9d0d-07cb36f89c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMEDIKA PAYOR PT 2-'])[2]/following::li[2]</value>
      <webElementGuid>cf240f83-8210-4f7f-ae9b-62fe144596f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMEDIKA PAYOR PT-AIA'])[2]/preceding::li[1]</value>
      <webElementGuid>44d5f935-7481-4b1e-8a7e-485f0ae802a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ADMEDIKA PAYOR PT-AIA INDIVIDU'])[2]/preceding::li[2]</value>
      <webElementGuid>cdbe7ca9-f033-4ce0-bc9b-44b86334ccb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[3]</value>
      <webElementGuid>815fbf05-c8f0-4169-9ac1-dfe306061358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-prescription_payment_insurance-result-dtkw-22042' and (text() = 'ADMEDIKA PAYOR PT- ' or . = 'ADMEDIKA PAYOR PT- ')]</value>
      <webElementGuid>d3d8ed63-f0dc-4dad-ab8c-be5528f67ada</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
