<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cari Peserta</name>
   <tag></tag>
   <elementGuidId>0309e4eb-0f15-4631-97e5-f751ecaafb54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-insurance_number_select2-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-insurance_number_select2-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0fbb1aa7-65be-4d1e-b28c-a6b2de669301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>1eb2278f-f24b-4917-9553-1f7bb781af28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-insurance_number_select2-container</value>
      <webElementGuid>1a0ae66a-7e5d-4484-ace7-fc035759e4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cari Peserta</value>
      <webElementGuid>7b19f237-9aaf-4b20-aaf2-3c956436e6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cari Peserta</value>
      <webElementGuid>0fa662b3-8569-4b4a-ac10-122be49e01fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-insurance_number_select2-container&quot;)</value>
      <webElementGuid>37300b30-1860-41c5-a517-bcad8170c15c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-insurance_number_select2-container']</value>
      <webElementGuid>d0934fa2-923c-434f-bdd3-08f60a91eb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='prescription-data']/div[4]/div/div/span/span/span/span</value>
      <webElementGuid>32fbedb0-3710-4c09-bb6c-7151f2a7fc11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Kartu'])[1]/following::span[4]</value>
      <webElementGuid>8b403a5e-7fdf-4f76-9a39-d4f79e81f776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat dokter harus diisi'])[1]/following::span[4]</value>
      <webElementGuid>91a98643-f82e-4b0d-86da-6057dc6a0ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Peserta*'])[1]/preceding::span[3]</value>
      <webElementGuid>233c5102-1214-40d4-89c5-0e92cced4eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. resep*'])[1]/preceding::span[3]</value>
      <webElementGuid>a68604b6-1c50-491a-89d9-71bc5a69066c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/span/span/span/span</value>
      <webElementGuid>287a72c3-0461-4e90-a689-14aec38101de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-insurance_number_select2-container' and @title = 'Cari Peserta' and (text() = 'Cari Peserta' or . = 'Cari Peserta')]</value>
      <webElementGuid>e13bc0ae-e7ae-425a-b9c9-6f1f5ff057b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
