<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ADMEDIKA PAYOR PT-</name>
   <tag></tag>
   <elementGuidId>3cc7f145-d1db-4961-a9fc-91fd26715ca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-prescription_payment_insurance-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3962432e-73f3-4ff2-af18-8288cce053ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>2f307083-b25b-414f-a8fa-401a02e3878b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-prescription_payment_insurance-container</value>
      <webElementGuid>4394527e-c4a3-41b2-a7c1-e62eaabff003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ADMEDIKA PAYOR PT- </value>
      <webElementGuid>b1e131b7-763b-4a2e-a20b-e8c00b223b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tittle</name>
      <type>Main</type>
      <value>-pilih jaminan-</value>
      <webElementGuid>b4d91883-2b4c-4c70-b453-3b52834c1723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ADMEDIKA PAYOR PT- </value>
      <webElementGuid>a470cc8a-e812-4f2e-896f-0e2886d2cb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-prescription_payment_insurance-container&quot;)</value>
      <webElementGuid>359ed379-eced-444e-b328-72272f617525</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-prescription_payment_insurance-container']</value>
      <webElementGuid>1eaf7d07-b2e5-49cf-8bb6-2c5f30f8d2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_prescription_3063']/div[3]/div/div[2]/span/span/span/span</value>
      <webElementGuid>1df26ceb-d62d-42d0-a795-6ad63cfb8288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kredit Resep'])[1]/following::span[4]</value>
      <webElementGuid>623c07db-6ec9-4c06-9642-b6929c26ed7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tunai'])[1]/following::span[4]</value>
      <webElementGuid>a47c9d3d-5177-4097-9a00-7d615eb99479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Pasien*'])[1]/preceding::span[3]</value>
      <webElementGuid>3da89414-275c-484a-89c8-f55d403428a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama pasien harus diisi'])[1]/preceding::span[3]</value>
      <webElementGuid>fc0c1076-628b-4a45-b0c5-a2bbab9c6b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>fc99db25-48f1-44c3-991a-a7282628757e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-prescription_payment_insurance-container' and @title = 'ADMEDIKA PAYOR PT- ' and (text() = 'ADMEDIKA PAYOR PT- ' or . = 'ADMEDIKA PAYOR PT- ')]</value>
      <webElementGuid>897fa6b8-4521-488b-8533-828d66b89648</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
