<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-pilih jaminan-</name>
   <tag></tag>
   <elementGuidId>b9f1ff28-2761-4215-86b7-b5b2ddbcc509</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-prescription_payment_insurance-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-prescription_payment_insurance-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5216d23c-8490-4f33-9f63-3ac1e7394781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>ea05209b-f2a4-4304-bad4-c7cc689a92cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-prescription_payment_insurance-container</value>
      <webElementGuid>5bc9625b-a6bb-412e-ad10-fdb1d6a7662b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-pilih jaminan-</value>
      <webElementGuid>0965ebb6-c6be-4f30-85e1-287e6742bf9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tittle</name>
      <type>Main</type>
      <value>-pilih jaminan-</value>
      <webElementGuid>de7f6478-a93c-41cb-9437-47615a8d9eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-pilih jaminan-</value>
      <webElementGuid>0e811449-cc26-4d4c-b99b-358966383610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-prescription_payment_insurance-container&quot;)</value>
      <webElementGuid>70cc2aec-a51a-4a16-ae87-cc3b3d06b822</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-prescription_payment_insurance-container']</value>
      <webElementGuid>3742f350-cb75-4f3a-aa5c-727e030d6592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_prescription_3063']/div[3]/div/div[2]/span/span/span/span</value>
      <webElementGuid>08862be0-7821-48d5-86ca-ca7dc3ce8503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kredit Resep'])[1]/following::span[4]</value>
      <webElementGuid>b4ced65b-99d2-4305-a3b9-b97c575ce1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tunai'])[1]/following::span[4]</value>
      <webElementGuid>259b4373-64aa-4dbc-a4c0-8292f8a177cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Pasien*'])[1]/preceding::span[3]</value>
      <webElementGuid>55cb9251-eadb-4195-a828-5fd16808b1e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama pasien harus diisi'])[1]/preceding::span[3]</value>
      <webElementGuid>87fa4668-6c8b-46a2-ac12-467f0435f12d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>e1410202-ef50-4af9-97a9-f60a99f4eece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-prescription_payment_insurance-container' and @title = '-pilih jaminan-' and (text() = '-pilih jaminan-' or . = '-pilih jaminan-')]</value>
      <webElementGuid>91f51cc4-ce1f-431a-ae08-ca2c82077e9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_prescription_3061']/div[3]/div/div[2]/span/span/span/span</value>
      <webElementGuid>c13b73a0-f77e-44d2-9ad8-3864cf3ca35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='edit_prescription_3059']/div[3]/div/div[2]/span/span/span/span</value>
      <webElementGuid>dc6c4865-5b31-4675-834a-c2d11f56131a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
