<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Kirim WA_lever</name>
   <tag></tag>
   <elementGuidId>1a1a1753-faba-4f2d-b6a5-a8f963878bd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='choose-receipt-modal']/div[2]/div[2]/div[3]/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>756937d6-dc18-44aa-8560-e91abbc9ee15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lever</value>
      <webElementGuid>b6e1463d-3ee9-44c7-9221-0fa82ce03b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choose-receipt-modal&quot;)/div[2]/div[@class=&quot;row option expres&quot;]/div[@class=&quot;col s3&quot;]/div[@class=&quot;switch&quot;]/label[1]/span[@class=&quot;lever&quot;]</value>
      <webElementGuid>7698d1c0-5728-4298-9689-ae1b9d63c6aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='choose-receipt-modal']/div[2]/div[2]/div[3]/div/label/span</value>
      <webElementGuid>77195686-da9c-40e6-8fe2-c8541166cc94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/label/span</value>
      <webElementGuid>0e062ef2-80a8-473b-b492-b90401d5c39b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
