<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td</name>
   <tag></tag>
   <elementGuidId>b9881e01-7dbf-4dfa-86ff-92dfdd0db587</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='payment-detail']/table/tbody/tr/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>cbf5c1c6-5d18-4cb0-80fa-bc63750a8a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>7px</value>
      <webElementGuid>cfbfd5a8-cace-417a-84ed-0dcf1c021376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-detail&quot;)/table[@class=&quot;bordered&quot;]/tbody[1]/tr[1]/td[4]</value>
      <webElementGuid>1fdf3e98-53e2-4df8-b277-c7f1c924096f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-detail']/table/tbody/tr/td[4]</value>
      <webElementGuid>b6662061-9ff9-4526-830b-8df2744b6596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPG .'])[1]/following::td[2]</value>
      <webElementGuid>5a758f51-cd6e-4a10-a4f7-0a2b98a8d6ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NAMA KARYAWAN'])[1]/following::td[4]</value>
      <webElementGuid>22dd1e21-c0e6-4d90-9d39-ed136a9bcd78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Putu Eka Putri Rahayu'])[1]/preceding::td[1]</value>
      <webElementGuid>ae117993-92dc-4a64-a881-faa5f98b09c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='alfi.kurniatin alfi.kurniatin'])[1]/preceding::td[3]</value>
      <webElementGuid>360f2a58-8ebc-4cf4-8d31-c9f6de7a212a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]</value>
      <webElementGuid>41fa876a-5575-4473-860b-4f036da06a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
